
var _homePageLayoutType="WelcomeDefault";var _welcomeCardSize=1;var _twitterCardSize=260;var _cloneTwitterFeed={};var _apiFirstScroller;var _apiSecondScroller;var _prevScrollPosition;var _SCROLL_POSITION_COOKIE;var _LAST_VIEW_COLUMN_COUNT=3;var _cookieFirstScrollerPosition=0;var _cookieSecondScrollerPosition=0;var _isCookie=false;var _isFirstScrollerReturning=false;var _isFirstScroll=true;var _isTabbed=false;var indexItems=0;var cardIndex=0;var _isFeatureLinkClicked=false;var leftPosition=0;var _scrollBehavior="DoNotRotate";var _secondScrollerItems;var _secondScrollerItemCards;var _secondScrollerCardsNotCloned;var _secondScrollerCardsNotClonedAnchors;$(document).ready(function(){if(/msie|MSIE 7/.test(navigator.userAgent)){var zoomLevel=GetIE7ZoomLevel();ConfigureCarouselBasedOnZoom(zoomLevel);setInterval(function(){var newZoom=GetIE7ZoomLevel();if(newZoom!=zoomLevel){zoomLevel=newZoom;ConfigureCarouselBasedOnZoom(newZoom);}},500);}
else if(typeof _apiFirstScroller!="undefined"&&typeof _apiSecondScroller!="undefined"){AcnTabbingEvent();}});function ConfigureCarouselBasedOnZoom(zoomLevel){if(zoomLevel!=100){DisableCarouselWhenZoomed();}else{EnableCarouselWhenZoomed();AcnTabbingEvent();}}
function GetIE7ZoomLevel(){var zoomLevel=100;if('deviceXDPI'in screen){if(screen.systemXDPI===undefined){if(document.body.getBoundingClientRect){var rect=document.body.getBoundingClientRect();var physicalW=rect.right-rect.left;var logicalW=document.body.offsetWidth;zoomLevel=Math.round((physicalW/logicalW)*100);}}}
return zoomLevel;}
function DisableCarouselWhenZoomed(){if(typeof _secondScrollerCardsNotClonedAnchors!=="undefined"){_secondScrollerCardsNotClonedAnchors.unbind('focus');_secondScrollerCardsNotClonedAnchors.unbind('keydown');_secondScrollerCardsNotClonedAnchors.unbind('mousedown');_secondScrollerCardsNotClonedAnchors.unbind('mouseout');$('#skipfooterlinkholder').unbind('keydown');$('#hp-scroll-button-left').prop('disabled',true);$('#hp-scroll-button-right').prop('disabled',true);var index=_apiSecondScroller.getIndex();for(x=0;x<_secondScrollerCardsNotCloned.length;x++){if((x!=index)&&(x!=index+1)&&(x!=index+2)){$('#SecondScroller .items .item:not(".cloned"):eq('+x+') a').prop('disabled',true);}}}
if((_scrollBehavior=="RotateContinously")||(_scrollBehavior=="RotateOnce")){_apiSecondScroller.stop();}}
function EnableCarouselWhenZoomed(){if(typeof _secondScrollerCardsNotClonedAnchors!=="undefined"){_secondScrollerCardsNotClonedAnchors.each(function(index){$(this).removeAttr('disabled');});}
$('#hp-scroll-button-left').removeAttr('disabled');$('#hp-scroll-button-right').removeAttr('disabled');}
function AcnTabbingEvent(){if(typeof _secondScrollerCardsNotCloned!=="undefined"){_secondScrollerCardsNotCloned.each(function(index){$(this).attr({CardIndex:index});});}
indexItems=_apiSecondScroller.getSize()-_LAST_VIEW_COLUMN_COUNT;if(typeof _secondScrollerCardsNotClonedAnchors!=="undefined"){_secondScrollerCardsNotClonedAnchors.focus(function(){if(_isFeatureLinkClicked){_isFeatureLinkClicked=false;return;}
_isTabbed=true;cardIndex=parseInt($(this).closest('.item').attr('CardIndex'));TabbingSeekTo(cardIndex,indexItems);_isTabbed=false;}).keydown(function(e){if(e.keyCode==9){_isTabbed=true;TabbingSeekTo(cardIndex,indexItems);_isTabbed=false;}}).mousedown(function(){_isFeatureLinkClicked=true;}).mouseout(function(){_isFeatureLinkClicked=false;});}
function TabbingSeekTo(cardIndex,indexItems){if(cardIndex<=indexItems)
_apiSecondScroller.seekTo(cardIndex,0);else
_apiSecondScroller.seekTo(indexItems,0);var firstScrollerNextIndex;if(cardIndex>_welcomeCardSize){firstScrollerNextIndex=_welcomeCardSize;}else{firstScrollerNextIndex=cardIndex;}
_apiFirstScroller.seekTo(firstScrollerNextIndex,0);}
$('#skipfooterlinkholder').keydown(function(e){if((e.keyCode==9)&&(e.shiftKey)){e.preventDefault();_isTabbed=true;if(cardIndex<=indexItems)
_apiSecondScroller.seekTo(cardIndex,0);else
_apiSecondScroller.seekTo(indexItems,0);_isTabbed=false;$('#SecondScroller .items .item:not(".cloned"):last a:last').focus();}});}
var _jsonWelcomeCard;var actualJsonWelcomeCard;$("#WelcomeDefault").hide();$("#WelcomeNoTab").hide();$("#WelcomeWithTab").hide();var overrideStyle=$("<style>.user-status .LoginNavigation .LoginNote a, .divdelimiterLiteral{color: #AADDEE;} .user-status .LoginNavigation .LoginNote a:hover{color:#ade;} .PrivacyCookiePolicyHomepage .PrivacyCookiePolicyMessage a{color: #AADDEE !important; font-weight: normal;} </style>");$("head").append(overrideStyle);function InitializeScrollers(scrollBehavior,scrollDelay,isCommunity){var initialFirstScrollerPosition=0;var initialSecondScrollerPosition=0;var previousSecondScrollerSize=0;if($.cookie){if($.cookie("s_uType")=="unknown"){_SCROLL_POSITION_COOKIE="_FS-Scroll";$.cookie('_FS-ScrollA',null);}
else{_SCROLL_POSITION_COOKIE="_FS-ScrollA";$.cookie('_FS-Scroll',null);}
var str=$.cookie(_SCROLL_POSITION_COOKIE);if(typeof str!=="string"&&str==null){str="0|0|0";}
var positions=str.split("|");initialFirstScrollerPosition=parseInt(positions[0]);initialSecondScrollerPosition=parseInt(positions[1]);if(positions.length==3){previousSecondScrollerSize=parseInt(positions[2]);}
else{previousSecondScrollerSize=0;}
if(initialFirstScrollerPosition<0||initialSecondScrollerPosition<0){initialFirstScrollerPosition=0;initialSecondScrollerPosition=0;}}
if(/msie|MSIE 7/.test(navigator.userAgent)){_scrollBehavior=scrollBehavior
if(GetIE7ZoomLevel()!=100){if((scrollBehavior=="RotateContinously")||(scrollBehavior=="RotateOnce"))
leftPosition=-310;initialFirstScrollerPosition=0;initialSecondScrollerPosition=0;}}
switch(_homePageLayoutType){case"WelcomeNoTab":_welcomeCardSize=2;$("#extraBottomScrollable").css("display","block");$("#extraTopScrollable").css("display","block");$("#bottomcarousel").css("height","259px");$(".EU-Privacy-Login").css("height","58px");$(".WelcomeWithTabHeader").css("height","22px");if(!$(".WelcomeNoTab")[0]){$("#extraBottomScrollable").remove();$("#extraTopScrollable").remove();$("div.items > div:first-child").remove();}
if(initialFirstScrollerPosition==1||initialFirstScrollerPosition>2){initialFirstScrollerPosition=2;}
break;case"WelcomeWithTab":_welcomeCardSize=2;$("#extraBottomScrollable").css("display","block");$("#extraTopScrollable").css("display","block");$("#bottomcarousel").css("height","259px");$(".EU-Privacy-Login").css("height","58px");$(".WelcomeWithTabHeader").css("height","22px");if(!$(".WelcomeWithTab")[0]){$("#extraBottomScrollable").remove();$("#extraTopScrollable").remove();$("div.items > div:first-child").remove();}
if(initialFirstScrollerPosition==1||initialFirstScrollerPosition>2){initialFirstScrollerPosition=2;}
break;default:$("div.items > div:first-child").remove();$("#extraTopScrollable").remove();$("#extraBottomScrollable").remove();break;}
function AdjustTwitterCardSize(scrollerSize,index){if(scrollerSize==2){switch(index){case 1:_twitterCardSize=880;break;case 0:_twitterCardSize=570;break;default:_twitterCardSize=880;break;}}else if(scrollerSize==3){switch(index){case 2:_twitterCardSize=880;break;case 1:_twitterCardSize=570;break;case 0:_twitterCardSize=260;break;default:_twitterCardSize=880;break;}}else if(scrollerSize==1){switch(index){default:_twitterCardSize=880;break;}}}
$("a.browse").fadeTo("fast",1);scrollDelay=parseInt(scrollDelay)*1000;var scrollSpeed=350;if(scrollBehavior!=="RotateContinously"&&scrollBehavior!=="RotateOnce"){$("#FirstScroller").scrollable({circular:false,mousewheel:false,keyboard:false,speed:scrollSpeed,initialIndex:initialFirstScrollerPosition,touch:false}).navigator();$("#SecondScroller").scrollable({circular:false,mousewheel:true,keyboard:false,speed:scrollSpeed,initialIndex:initialSecondScrollerPosition,lastviewcolumncount:_LAST_VIEW_COLUMN_COUNT});}else{$("#FirstScroller").scrollable({circular:false,mousewheel:false,keyboard:false,speed:scrollSpeed,initialIndex:initialFirstScrollerPosition,touch:false}).navigator().autoscroll({interval:scrollDelay,autoplay:false,autopause:false});$("#SecondScroller").scrollable({circular:true,mousewheel:true,keyboard:false,speed:scrollSpeed,initialIndex:initialSecondScrollerPosition,lastviewcolumncount:_LAST_VIEW_COLUMN_COUNT}).autoscroll({interval:scrollDelay,autoplay:true,autopause:true});}
_secondScrollerItems=$("#SecondScroller > .items");_secondScrollerItemCards=_secondScrollerItems.find("> .item");_secondScrollerCardsNotCloned=_secondScrollerItemCards.not(".cloned");_secondScrollerCardsNotClonedAnchors=_secondScrollerCardsNotCloned.find("a");if((/msie|MSIE 7/.test(navigator.userAgent))&&(GetIE7ZoomLevel()!=100)){$('#bottomcarousel .items').css('left',leftPosition);}
_apiFirstScroller=$("#FirstScroller").data("scrollable");_apiSecondScroller=$("#SecondScroller").data("scrollable");if(previousSecondScrollerSize!=_apiSecondScroller.getSize()&&initialSecondScrollerPosition>0){var currentSecondScrollerPosition=0;if(previousSecondScrollerSize<_apiSecondScroller.getSize()){currentSecondScrollerPosition=_apiSecondScroller.getSize()-previousSecondScrollerSize+initialSecondScrollerPosition;}
else{currentSecondScrollerPosition=Math.abs(previousSecondScrollerSize-_apiSecondScroller.getSize()-initialSecondScrollerPosition);}
_apiSecondScroller.seekTo(currentSecondScrollerPosition,0);initialSecondScrollerPosition=currentSecondScrollerPosition;}
if(_welcomeCardSize==2){if(_apiSecondScroller.getIndex()<2){_apiFirstScroller.seekTo(0,0);}
else{_apiFirstScroller.seekTo(2,0);}}
if(_homePageLayoutType!="WelcomeDefault"&&actualJsonWelcomeCard._tabs._articles==null&&actualJsonWelcomeCard._tabs._sites==null){$('div#welcome').remove();$('div#extraBottomScrollable').remove();$('div#firstExtraTopScrollable').remove();$('div#extraTopScrollable').remove();$('div#firstTopScrollable').remove();}
AdjustTwitterCardSize(_apiFirstScroller.getSize(),initialFirstScrollerPosition);AnimateTwitter(_twitterCardSize);if((_apiSecondScroller.getSize()<=3)||(initialSecondScrollerPosition>=_apiSecondScroller.getSize()-_LAST_VIEW_COLUMN_COUNT)){$('#hp-scroll-button-right').hide();}
if(initialSecondScrollerPosition==0){$('#hp-scroll-button-left').addClass("disabled");}else{$('#hp-scroll-button-left').removeClass("disabled");}
$('#hp-scroll-button-right').attr("rel","home-scroll");$('#hp-scroll-button-left').attr("rel","home-scroll");_secondScrollerItems.find(".cloned a").each(function(index){$(this).attr("tabIndex","-1");});_apiSecondScroller.onBeforeSeek(function(event,index){var currentPositionSecondScroller=this.getIndex();var lastPositionSecondScroller=this.getSize()-_LAST_VIEW_COLUMN_COUNT;switch(scrollBehavior){case"RotateContinously":if(currentPositionSecondScroller==lastPositionSecondScroller&&!_isFirstScrollerReturning&&!_isTabbed){_apiFirstScroller.seekTo(_apiFirstScroller.getIndex(),0);_isFirstScrollerReturning=true;this.begin();_isFirstScrollerReturning=false;_apiFirstScroller.begin();return false;}
break;case"RotateOnce":if(currentPositionSecondScroller==lastPositionSecondScroller&&!_isFirstScrollerReturning&&_isFirstScroll&&!_isTabbed){_apiFirstScroller.seekTo(_apiFirstScroller.getIndex(),0);_isFirstScrollerReturning=true;this.begin();this.stop();_isFirstScrollerReturning=false;_apiFirstScroller.begin();_apiFirstScroller.stop();_isFirstScroll=false;return false;}
break;default:break;}
_prevScrollPosition=this.getIndex();if(_welcomeCardSize==2&&index==1&&!_isTabbed){_apiSecondScroller.seekTo(2-this.getIndex(),scrollSpeed*1.4);_apiFirstScroller.seekTo(2-_apiFirstScroller.getIndex(),scrollSpeed*1.4);return false;}
if(_welcomeCardSize!=2&&this.getIndex()<=this.getSize()-_LAST_VIEW_COLUMN_COUNT&&!_isTabbed){_apiFirstScroller.seekTo(index);}
if(index>=this.getSize()-_LAST_VIEW_COLUMN_COUNT){$('#hp-scroll-button-right').hide();}else{$('#hp-scroll-button-right').show();}
if(index<1){$('#hp-scroll-button-left').addClass("disabled");}else{$('#hp-scroll-button-left').removeClass("disabled");}});_apiFirstScroller.onSeek(function(event,index){var scrollerSize=this.getSize();AdjustTwitterCardSize(scrollerSize,index);AnimateTwitter(_twitterCardSize);});_apiSecondScroller.onSeek(function(event,index){var currentPositionSecondScroller=this.getIndex();var lastPositionSecondScroller=this.getSize()-_LAST_VIEW_COLUMN_COUNT;if($.cookie){$.cookie(_SCROLL_POSITION_COOKIE,_apiFirstScroller.getIndex()+"|"+this.getIndex()+"|"+this.getSize());}
if(typeof window.s_code!="undefined"&&window.s_code!=null&&!_isCookie&&!_isTabbed){AcnHomepageTrackScrollChanged(_prevScrollPosition,currentPositionSecondScroller,this.getSize()-1,_homePageLayoutType,event);}
_isCookie=false;});}
function delay(time){var date1=new Date();var date2=new Date();while(date2.valueOf()<date1.valueOf()+time){date2=new Date();}}
function AnimateTwitter(containerWidth){var divTwitterFeed=$(".TwitterFeed").val();if(divTwitterFeed!=null||typeof(divTwitterFeed)!='undefined'){var apiTwitterTabs=$("#TwitterFeedTabs").data("tabs");var apiTwitterSlider=$("#TwitterFeedTabs").data("slideshow");var size=260;if(typeof(apiTwitterSlider)!=='undefined'){apiTwitterSlider.stop();apiTwitterTabs.destroy();$('.TwitterCardDesc').html(_cloneTwitterFeed.html());}
$(".TwitterFeedItem").css("width",containerWidth);if(containerWidth){size=containerWidth;}
var firstVisibleTweet=$('#TwitterFeed > div:visible:first a');var trunc=truncate(firstVisibleTweet,size);firstVisibleTweet.text(trunc);$("#TwitterFeed").fadeTo(2000,1);$("#TwitterFeedTabs").tabs(".TwitterFeedItem",{effect:'fade',fadeOutSpeed:1000,fadeInSpeed:1000,rotate:true,isTwitterFeed:true,twitterFeedSize:size,autopause:false,clickable:false}).slideshow({interval:5000});apiTwitterSlider=$("#TwitterFeedTabs").data("slideshow");apiTwitterSlider.play();}}
function getAcnCookie(key){var keyValue=document.cookie.match('(^|;) ?'+key+'=([^;]*)(;|$)');return keyValue?keyValue[2]:null;}
function getFeaturedSectionLayoutType(actualJsonObject){var homePageLayoutType="WelcomeDefault";if(typeof actualJsonObject!==undefined&&typeof(actualJsonObject)==='object'){if(actualJsonObject._welcomeCardHeader._anonymousDesc==null){try{if(actualJsonObject._tabs._sites!=null&&actualJsonObject._tabs._articles!=null){homePageLayoutType="WelcomeWithTab";}
else if(actualJsonObject._tabs._sites!=null||actualJsonObject._tabs._articles!=null){homePageLayoutType="WelcomeNoTab";}}catch(e){}}}
return homePageLayoutType;}
function CreateMainTabbing(title,id){if(!IsNullOrEmpty(title)){$(id).children().append(title);}else{$(id).remove();}}
function IsNullOrEmpty(string){if(string==null||typeof(string)=="undefined"||string==""){return true;}else{return false;}}
function CreateThumbnailTabbing(TabVar,Type){var linkindex;var imageindex=1;var articleLink;var siteLink;for(index in TabVar){var thumbImage=TabVar[index]._thumbnailImage._src.replace(/^.*\/\/[^\/]+/,'');var largeImage=TabVar[index]._largeImage._src.replace(/^.*\/\/[^\/]+/,'');if(TabVar[index]._content==null){TabVar[index]._content="";}
if(TabVar[index]._header==null){TabVar[index]._header="";}
if(TabVar[index]._thumbnailImage._src==null){TabVar[index]._thumbnailImage._src="";}
if(TabVar[index]._thumbnailImage._link._title==null){TabVar[index]._thumbnailImage._link._title="";}
if(TabVar[index]._thumbnailImage._href==null){TabVar[index]._thumbnailImage._href="";}
if(TabVar[index]._thumbnailImage._link._alt==null){TabVar[index]._thumbnailImage._link._alt="";}
if(TabVar[index]._thumbnailImage._link._rel==null){TabVar[index]._thumbnailImage._link._rel="";}
if(TabVar[index]._largeImage._src==null){TabVar[index]._largeImage._src="";}
if(TabVar[index]._largeImage._link._title==null){TabVar[index]._largeImage._link._title="";}
if(TabVar[index]._largeImage._href==null){TabVar[index]._largeImage._href="";}
if(TabVar[index]._largeImage._link._alt==null){TabVar[index]._largeImage._link._alt="";}
if(TabVar[index]._largeImage._link._rel==null){TabVar[index]._largeImage._link._rel="";}
if(Type=="_articles"){var pos=parseInt(imageindex)-1;$("#articles-thumbnail-img"+imageindex).attr("rel","home-article-thumb"+"-"+pos);$("#articles-thumbnail-img"+imageindex).append("<div class='thumbnail-border'><img src='"+thumbImage+"' title='"+TabVar[index]._thumbnailImage._link._title+"' alt='"+TabVar[index]._thumbnailImage._link._alt+"' height='45px' width='45px'/></div>");if(TabVar[index]._isNotUnderline.toLowerCase()=="n"){$("#articles-large-img"+imageindex).append("<a href='"+TabVar[index]._largeImage._link._href+"' title='"+TabVar[index]._header+"' rel='"+TabVar[index]._largeImage._link._rel+"' name='"+TabVar[index]._largeImage._link._name+"'>"+"<img src='"+largeImage+"' title='"+TabVar[index]._largeImage._link._title+"' alt='"+TabVar[index]._largeImage._link._alt+"' rel='"+TabVar[index]._largeImage._link._rel+"' height='164px' width='109px'/>"+"</a>");$("#articles-content"+imageindex).append("<h2><a href='"+TabVar[index]._largeImage._link._href+"' title='"+TabVar[index]._header+"' rel='"+TabVar[index]._largeImage._link._rel+"' name='"+TabVar[index]._largeImage._link._name+"'>"+TabVar[index]._header+"</a></h2><p>"+TabVar[index]._content+"</p><br/>");}else{$("#articles-large-img"+imageindex).append("<img src='"+largeImage+"' title='"+TabVar[index]._largeImage._link._title+"' alt='"+TabVar[index]._largeImage._link._alt+"' rel='"+TabVar[index]._largeImage._link._rel+"' height='164px' width='109px'/>");$("#articles-content"+imageindex).append("<h2>"+TabVar[index]._header+"</h2><p>"+TabVar[index]._content+"</p><br/>");}
if(TabVar[index]._links.length>0){articleLink="";for(linkindex in TabVar[index]._links){if(TabVar[index]._links[linkindex]._name==null){TabVar[index]._links[linkindex]._name="";}
if(TabVar[index]._links[linkindex]._title==null){TabVar[index]._links[linkindex]._title="";}
if(TabVar[index]._links[linkindex]._href==null){TabVar[index]._links[linkindex]._href="";}
if(TabVar[index]._links[linkindex]._alt==null){TabVar[index]._links[linkindex]._alt="";}
if(TabVar[index]._links[linkindex]._rel==null){TabVar[index]._links[linkindex]._rel="";}
if(TabVar[index]._links[linkindex]._text==null){TabVar[index]._links[linkindex]._text="";}
articleLink+="<p class='articleLink'><a name='"+TabVar[index]._links[linkindex]._name+"' title='"+TabVar[index]._links[linkindex]._title+"' href='"+TabVar[index]._links[linkindex]._href+"' alt='"+TabVar[index]._links[linkindex]._alt+"\' rel='"+"home-articles:products_featured-"+index+"'>"+TabVar[index]._links[linkindex]._text+"</a></p>";}
$("#articles-content"+imageindex).append("<div class='linkContainer'>"+articleLink+"</div>");}}else{var pos=parseInt(imageindex)-1;$("#sites-thumbnail-img"+imageindex).attr("rel","home-site-thumb"+"-"+pos);$("#sites-thumbnail-img"+imageindex).append("<div class='thumbnail-border'><img src='"+thumbImage+"' title='"+TabVar[index]._thumbnailImage._link._title+"' alt='"+TabVar[index]._thumbnailImage._link._alt+"' height='45px' width='45px'/></div>");if(TabVar[index]._isNotUnderline.toLowerCase()=="n"){$("#sites-large-img"+imageindex).append("<a href='"+TabVar[index]._largeImage._link._href+"' title='"+TabVar[index]._header+"' rel='"+TabVar[index]._largeImage._link._rel+"' name='"+TabVar[index]._largeImage._link._name+"'>"+"<img src='"+largeImage+"' title='"+TabVar[index]._largeImage._link._title+"' alt='"+TabVar[index]._largeImage._link._alt+"' rel='"+TabVar[index]._largeImage._link._rel+"' height='164px' width='109px'/>"+"</a>");$("#sites-content"+imageindex).append("<h2><a href='"+TabVar[index]._largeImage._link._href+"' title='"+TabVar[index]._header+"' rel='"+TabVar[index]._largeImage._link._rel+"' name='"+TabVar[index]._largeImage._link._name+"'>"+TabVar[index]._header+"</a></h2><p>"+TabVar[index]._content+"</p><br/>");}else{$("#sites-large-img"+imageindex).append("<img src='"+largeImage+"' title='"+TabVar[index]._largeImage._link._title+"' alt='"+TabVar[index]._largeImage._link._alt+"' rel='"+TabVar[index]._largeImage._link._rel+"' height='164px' width='109px'/>");$("#sites-content"+imageindex).append("<h2>"+TabVar[index]._header+"</h2><p>"+TabVar[index]._content+"</p><br/>");}
if(TabVar[index]._links.length>0){siteLink="";for(linkindex in TabVar[index]._links){if(TabVar[index]._links[linkindex]._name==null){TabVar[index]._links[linkindex]._name="";}
if(TabVar[index]._links[linkindex]._title==null){TabVar[index]._links[linkindex]._title="";}
if(TabVar[index]._links[linkindex]._href==null){TabVar[index]._links[linkindex]._href="";}
if(TabVar[index]._links[linkindex]._alt==null){TabVar[index]._links[linkindex]._alt="";}
if(TabVar[index]._links[linkindex]._rel==null){TabVar[index]._links[linkindex]._rel="";}
if(TabVar[index]._links[linkindex]._text==null){TabVar[index]._links[linkindex]._text="";}
siteLink+="<p class='siteLink'><a name='"+TabVar[index]._links[linkindex]._name+"' title='"+TabVar[index]._links[linkindex]._title+"' href='"+TabVar[index]._links[linkindex]._href+"' alt='"+TabVar[index]._links[linkindex]._alt+"' rel='"+"home-sites-"+index+"'>"+TabVar[index]._links[linkindex]._text+"</a></p>";}
$("#sites-content"+imageindex).append("<div class='linkContainer'>"+siteLink+"</div>");}}
imageindex=imageindex+1;}
if(TabVar.length<=1){if(Type=="_articles"){document.getElementById("articles-inner-css-tabs-thumbnails").style.display="none";var articleLinkContainer=$("#articles-content1 .linkContainer");if(articleLinkContainer.html()!=null){articleLinkContainer.css('margin-bottom','-3px');}}else{document.getElementById("sites-inner-css-tabs-thumbnails").style.display="none";var sitesLinkContainer=$("#sites-content1 .linkContainer");if(sitesLinkContainer.html()!=null){sitesLinkContainer.css('margin-bottom','-3px');}}}}
function CreateTabbingInNoTab(TabVar,Type){var linkindex;var imageindex=1;var siteArticleLink;for(index in TabVar){var thumbImage=TabVar[index]._thumbnailImage._src.replace(/^.*\/\/[^\/]+/,'');var largeImage=TabVar[index]._largeImage._src.replace(/^.*\/\/[^\/]+/,'');if(TabVar[index]._content==null){TabVar[index]._content="";}
if(TabVar[index]._header==null){TabVar[index]._header="";}
if(TabVar[index]._thumbnailImage._src==null){TabVar[index]._thumbnailImage._src="";}
if(TabVar[index]._thumbnailImage._link._title==null){TabVar[index]._thumbnailImage._link._title="";}
if(TabVar[index]._thumbnailImage._href==null){TabVar[index]._thumbnailImage._href="";}
if(TabVar[index]._thumbnailImage._link._alt==null){TabVar[index]._thumbnailImage._link._alt="";}
if(TabVar[index]._thumbnailImage._link._rel==null){TabVar[index]._thumbnailImage._link._rel="";}
if(TabVar[index]._largeImage._src==null){TabVar[index]._largeImage._src="";}
if(TabVar[index]._largeImage._link._title==null){TabVar[index]._largeImage._link._title="";}
if(TabVar[index]._largeImage._href==null){TabVar[index]._largeImage._href="";}
if(TabVar[index]._largeImage._link._alt==null){TabVar[index]._largeImage._link._alt="";}
if(TabVar[index]._largeImage._link._rel==null){TabVar[index]._largeImage._link._rel="";}
var pos=parseInt(imageindex)-1;$("#thumbnail-img"+imageindex).attr("rel","home"+Type.replace("_","-").replace("es","e")+"-thumb-"+pos);$("#thumbnail-img"+imageindex).append("<div class='thumbnail-border'><img src='"+thumbImage+"' title='"+TabVar[index]._thumbnailImage._link._title+"' alt='"+TabVar[index]._thumbnailImage._link._alt+"' height='45px' width='45px'/></div>");if(TabVar[index]._isNotUnderline.toLowerCase()=="n"){$("#large-img"+imageindex).append("<a href='"+TabVar[index]._largeImage._link._href+"' title='"+TabVar[index]._header+"' rel='"+TabVar[index]._largeImage._link._rel+"' name='"+TabVar[index]._largeImage._link._name+"'>"+"<img src='"+largeImage+"' title='"+TabVar[index]._largeImage._link._title+"' alt='"+TabVar[index]._largeImage._link._alt+"' rel='"+TabVar[index]._largeImage._link._rel+"' height='164px' width='109px'/>"+"</a>");$("#content"+imageindex).append("<h2><a href='"+TabVar[index]._largeImage._link._href+"' title='"+TabVar[index]._header+"' rel='"+TabVar[index]._largeImage._link._rel+"' name='"+TabVar[index]._largeImage._link._name+"'>"+TabVar[index]._header+"</a></h2><p>"+TabVar[index]._content+"</p><br/>");}else{$("#large-img"+imageindex).append("<img src='"+largeImage+"' title='"+TabVar[index]._largeImage._link._title+"' alt='"+TabVar[index]._largeImage._link._alt+"' rel='"+TabVar[index]._largeImage._link._rel+"' height='164px' width='109px'/>");$("#content"+imageindex).append("<h2>"+TabVar[index]._header+"</h2><p>"+TabVar[index]._content+"</p><br/>");}
if(TabVar[index]._links.length>0){siteArticleLink="";for(linkindex in TabVar[index]._links){if(TabVar[index]._links[linkindex]._name==null){TabVar[index]._links[linkindex]._name="";}
if(TabVar[index]._links[linkindex]._title==null){TabVar[index]._links[linkindex]._title="";}
if(TabVar[index]._links[linkindex]._href==null){TabVar[index]._links[linkindex]._href="";}
if(TabVar[index]._links[linkindex]._alt==null){TabVar[index]._links[linkindex]._alt="";}
if(TabVar[index]._links[linkindex]._rel==null){TabVar[index]._links[linkindex]._rel="";}
if(TabVar[index]._links[linkindex]._text==null){TabVar[index]._links[linkindex]._text="";}
siteArticleLink+="<p class='siteArticleLink'><a name='"+TabVar[index]._links[linkindex]._name+"' title='"+TabVar[index]._links[linkindex]._title+"' href='"+TabVar[index]._links[linkindex]._href+"' alt='"+TabVar[index]._links[linkindex]._alt+"' rel='"+"home"+Type.replace("_","-")+":products_featured-"+index+"'>"+TabVar[index]._links[linkindex]._text+"</a></p>";}
$("#content"+imageindex).append("<div class='linkContainer'>"+siteArticleLink+"</div>");}
imageindex=imageindex+1;}
if(TabVar.length<=1){document.getElementById("inner-css-tabs-thumbnails").style.display="none";}}
function RemoveDottedLines(){var links=document.getElementById('SecondScroller').getElementsByTagName('a');for(var i=0;i<links.length;i++){links[i].onmousedown=function(){this.blur();return false;}
links[i].onclick=function(){this.blur();}}}
function SetLocationForRightAlignedImageOrNoImageReadMoreDiv(){if($(".FeaturedGenericCardDescContainer-NoImage")[0]){$('.FeaturedGenericCardDescContainer-NoImage').siblings().css('left','0px');}
if($(".fg-img-right")[0]){$('.fg-img-right').parent().parent().addClass('FeaturedGenericCardImg_Right');$('.FeaturedGenericCardImg_Right').siblings().css('left','0px');}};(function($,window,document,undefined){var pluginName='AcnHomepageFeaturedSection',defaults={layoutType:_homePageLayoutType,jsonData:_jsonWelcomeCard};function AcnHomepageFeaturedSection(element,options){this.element=element;this.options=$.extend({},defaults,options);this._defaults=defaults;this._name=pluginName;this.init();}
AcnHomepageFeaturedSection.prototype={init:function(){var jsonData=this.options.jsonData;var layoutType=this.options.layoutType;var $element=$(this.element);$element.hide();if(jsonData!==undefined&&typeof(jsonData)==='object'){}else{this.options.jsonData=_jsonWelcomeCard;}
this.update();},update:function(el,options){var $element=$(this.element);var jsonData=this.options.jsonData;var layoutType=this.options.layoutType;try{var _interestLink="";var pathname=window.location.pathname.toLowerCase();var toplevel_site=pathname.split('/')[1];var seeRecommendationAnchor="<a href='/"+toplevel_site+"/registration/Pages/article-recommendations.aspx"+"' class='seeRecommendations'>"+jsonData._welcomeCardHeader._recognizedAuthenticatedDesc+"</a>"
switch(layoutType){case"WelcomeNoTab":var obj=jsonData._tabs;var _updateMyPasswordLink;_interestLink="https://"+String(document.domain)+jsonData._myPreferencesLink._href;$("#WelcomeNoTabTitle").text(jsonData._welcomeCardHeader._title);$("#WelcomeNoTabDesc").append(seeRecommendationAnchor);$('a[id$="EditMyPreferenceLink"]').attr('href',_interestLink);if(jsonData._updateMyPassword!=null){_updateMyPasswordLink="https://"+String(document.domain)+jsonData._updateMyPassword._href;$('a[id$="UpdateMyPasswordLink"]').attr('href',_updateMyPasswordLink);}
for(var prop in obj){if(obj.hasOwnProperty(prop)){switch(prop){case"_sites":if(obj._sites!=null){CreateTabbingInNoTab(obj._sites._items,prop);$('a[id*="EditMyPreferenceLink"]').attr('rel',"home-sites");$('a[id*="UpdateMyPasswordLink"]').attr('rel',"home-sites");}
break;case"_articles":if(obj._articles!=null){CreateTabbingInNoTab(obj._articles._items,prop);$('a[id*="EditMyPreferenceLink"]').attr('rel',"home-articles");$('a[id*="UpdateMyPasswordLink"]').attr('rel',"home-articles");}
break;default:break;}}}
$("div.inner-css-tabs").tabs("div.inner-css-tab-pane",{onClick:function(event,tabIndex){var tabTitle=$('a[id*="EditMyPreferenceLink"]').attr('rel');var dashIndex=tabTitle.indexOf('-',5);if(dashIndex>-1){tabTitle=tabTitle.substring(0,dashIndex);}
$('a[id*="EditMyPreferenceLink"]').attr('rel',tabTitle+'-'+tabIndex);$('a[id*="UpdateMyPasswordLink"]').attr('rel',tabTitle+'-'+tabIndex);if(typeof window.s_code!="undefined"&&window.s_code!=null){HandleBodyClick(event);TrackProductsImpression(RetrieveProductsImpression($('div.WelcomeNoTab')));}
if(/msie|MSIE 6/.test(navigator.userAgent)){$(".linkContainer").fadeTo('fast',1);}}});$("#WelcomeDefault").hide();$("#WelcomeNoTab").show();break;case"WelcomeWithTab":var obj=jsonData._tabs;var title="";var id="";_interestLink="https://"+String(document.domain)+jsonData._myPreferencesLink._href;$("#WelcomeWithTabTitle").text(jsonData._welcomeCardHeader._title);$("#WelcomeWithTabDesc").append(seeRecommendationAnchor);$('a[id$="EditMyPreferenceLinkWithTab"]').attr('href',_interestLink);if(jsonData._updateMyPassword!=null){$('a[id$="UpdateMyPasswordLink"]').hide();}
for(var prop in obj){if(obj.hasOwnProperty(prop)){switch(prop){case"_title":id="#Viewing";title=obj._title;CreateMainTabbing(title,id);break;case"_sites":id="#Sites";title=obj._sites._title;CreateMainTabbing(title,id);var sites=obj._sites._items;var sortedSites=[];for(var i=0;i<sites.length;i++){var s=sites[i]._largeImage._link._href;var idx=s.indexOf("network");if(idx!=-1){if(s.substring(idx+7)==""||s.substring(idx+7)=="/"){sortedSites[sortedSites.length]=sites[i];}}}
for(var i=0;i<sites.length;i++){var s=sites[i]._largeImage._link._href;var idx=s.indexOf("network");if(idx!=-1){if(s.substring(idx+7)!=""&&s.substring(idx+7)!="/"){sortedSites[sortedSites.length]=sites[i];}}}
for(var i=0;i<sites.length;i++){var s=sites[i]._largeImage._link._href;var idx=s.indexOf("network");if(idx==-1){sortedSites[sortedSites.length]=sites[i];}}
if(obj._sites._items.length>0){CreateThumbnailTabbing(sortedSites,prop);}
break;case"_articles":id="#Articles";title=obj._articles._title;CreateMainTabbing(title,id);if(obj._articles._items.length>0){CreateThumbnailTabbing(obj._articles._items,prop);}
break;default:break;}}}
$("#Sites a").attr('rel',"sites");$("#Articles a").attr('rel',"articles");$("ul.main-css-tabs").tabs("div.main-css-tab-pane",{onClick:function(event,tabIndex){var tabTitle="home";tabTitle=this.getCurrentTab().text();var apiInnerTabs=$("div.inner-css-tabs:visible").data("tabs");if(tabTitle){tabTitle="home-"+tabTitle.toLowerCase();if(apiInnerTabs){tabTitle=tabTitle+"-"+apiInnerTabs.getIndex();}
$('a[id*="EditMyPreferenceLink"]').attr('rel',tabTitle);$('a[id*="UpdateMyPasswordLink"]').attr('rel',tabTitle);}
if(typeof window.s_code!="undefined"&&window.s_code!=null){HandleBodyClick(event);TrackProductsImpression(RetrieveProductsImpression($('div.WelcomeWithTab')));}}});$("div.inner-css-tabs").tabs("div.inner-css-tab-pane",{onClick:function(event,tabIndex){var tabTitle=$('a[id*="EditMyPreferenceLink"]').attr('rel');tabTitle=(tabTitle.indexOf("home-sites")>=0)?"home-sites":"home-articles";$('a[id*="EditMyPreferenceLink"]').attr('rel',tabTitle+'-'+tabIndex);$('a[id*="UpdateMyPasswordLink"]').attr('rel',tabTitle+'-'+tabIndex);if(typeof window.s_code!="undefined"&&window.s_code!=null){HandleBodyClick(event);TrackProductsImpression(RetrieveProductsImpression($('div.WelcomeWithTab')));}
if(/msie|MSIE 6/.test(navigator.userAgent)){$(".linkContainer").fadeTo('fast',1);}}});$("#WelcomeDefault").hide();$("#WelcomeWithTab").show();break;default:break;}}catch(e){}
this.display();if(layoutType!="WelcomeDefault"){var welcomeTabTitle="";var welcomeTabDesc="";var welcomeHeader="";if(layoutType=="WelcomeWithTab"){welcomeTabTitle=$('#WelcomeWithTabTitle');welcomeTabDesc=$('#WelcomeWithTabDesc');welcomeHeader=$('.WelcomeWithTabHeader');}
else if(layoutType=="WelcomeNoTab"){welcomeTabTitle=$('#WelcomeNoTabTitle');welcomeTabDesc=$('#WelcomeNoTabDesc');welcomeHeader=$('.WelcomeNoTabHeader');}
var welcomeTitle=jsonData._welcomeCardHeader._title;var commaIndex=welcomeTitle.indexOf(',');var welcomeText=welcomeTitle.substr(0,commaIndex);if(/msie|MSIE 7/.test(navigator.userAgent)||/msie|MSIE 6/.test(navigator.userAgent)){welcomeTabDesc.removeAttr('style');welcomeTabTitle.hide();welcomeTabDesc.width(welcomeTabDesc.width());welcomeTabTitle.show();}
if(welcomeTabTitle.width()>=welcomeHeader.width()-parseInt(welcomeTabDesc.css('margin-left'))-welcomeTabDesc.width()){welcomeTabTitle.text(welcomeText+".");}}},display:function(){$(document).ready(function(){RemoveDottedLines();SetLocationForRightAlignedImageOrNoImageReadMoreDiv();if(typeof _secondScrollerItems!=="undefined"){_secondScrollerItems.each(function(index){$(this).find(".FeaturedGenericCard a").each(function(){$(this).attr("rel","products"+"-"+index);});});}
if($("a[id*=RegisterNowLink]").text()!=''){$("a[id*=RegisterNowLink]").click(function(){$("a[id*=RegisterNowLink]").attr('target','_self');});if($('.LoginName').text()!=''){$('.PrivacyCookiePolicyHomepage .PrivacyCookiePolicyMessage').css("position","absolute");$('.PrivacyCookiePolicyHomepage .PrivacyCookiePolicyMessage').css("top","8px");}}});$(window).load(function(){if(typeof window.s_code!="undefined"&&window.s_code!=null){window.AcnHomepageTrackPageLoad();}});$(this.element).show();}};$.fn[pluginName]=function(options){var args=arguments;if(options===undefined||typeof options==='object'){return this.each(function(){if(!$.data(this,'plugin_'+pluginName)){$.data(this,'plugin_'+pluginName,new AcnHomepageFeaturedSection(this,options));}});}else if(typeof options==='string'&&options[0]!=='_'&&options!=='init'){return this.each(function(){var instance=$.data(this,'plugin_'+pluginName);if(instance instanceof AcnHomepageFeaturedSection&&typeof instance[options]==='function'){instance[options].apply(instance,Array.prototype.slice.call(args,1));}});}}})(jQuery,window,document);