
function isTabletBrowser(){if(navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/Android/i)){return true;}
return false;}
$(document).ready(function(){var browserUsed=navigator.userAgent.toLowerCase();if((browserUsed.indexOf('ipad')>-1)){if(TnT_CurrentLayout=="Homepage"){$(".drop-down ul li.primaryNavItem a").prepend("<img alt='red-arrow' src='/PublishingImages/arrow-right-a13.png' style='position:relative;top:1px;margin:0px 5px 0px -15px;float:left' />");$(".drop-down ul li div.colspanNavItem a").prepend("<img alt='red-arrow' src='/PublishingImages/arrow-right-a13.png' style='position:relative;top:0px;margin:4px 0px 0px -14px;float:left;' />");}else{$(".drop-down ul li a").css("background","none");$(".drop-down ul li.primaryNavItem a").prepend("<img alt='white-arrow' src='/PublishingImages/white-arrow.gif' style='position:relative;top:1px;margin:0px 0px 0px -18px;float:left;' />");$(".drop-down ul li div.colspanNavItem a").prepend("<img alt='white-arrow' src='/PublishingImages/white-arrow.gif' style='position:relative;top:1px;margin:0px 0px 0px -18px;float:left;' />");}}
if((browserUsed.indexOf('chrome')>-1)||(browserUsed.indexOf('safari')>-1))
{$('.page .footer .careers .footer-nav').css('-webkit-text-size-adjust','auto');$('.page .footer .footer-nav, .outlook-page .footer .footer-nav').css('-webkit-text-size-adjust','auto');}
if(window.location.href.indexOf("/cn-zh/")>0&&(clientBrowser.browser.ie==7||clientBrowser.browser.ie==9))
{$('.allArticlesSingleViewContainer .ArticleReadMore .whitearrow-link').css('padding-top','4px');}
var url=window.location.href.toString().toLowerCase();if(url.indexOf("edit.")<0){var headID=document.getElementsByTagName("head")[0];var cssNode=document.createElement('link');cssNode.type='text/css';cssNode.rel='stylesheet';cssNode.href='/_layouts/Accenture/Styles/Hide_LiveSiteOnly.css';headID.appendChild(cssNode);}
$(window).resize(function(){if(/msie|MSIE 7/.test(navigator.userAgent)){setTimeout(function(){setLeftCoordinateLoginNavigationMenu();},1000);}else{setLeftCoordinateLoginNavigationMenu();}});var displayCountryLanguageSelector=false;var isMouseOnHover=false;$('.country-language-selector .control-selector').click(showCountryLanguageSelector);$('.country-language-selector .control-selector .drop-button').mouseover(mouseHoverTrue);$('.country-language-selector .control-selector .drop-button').mouseout(mouseHoverFalse);$('.country-language-selector .control-selector .icon-flag').mouseover(mouseHoverTrue);$('.country-language-selector .control-selector .icon-flag').mouseout(mouseHoverFalse);$(".country-language-selector .dropdown-selector").mouseover(mouseHoverTrue);$(".country-language-selector .dropdown-selector").mouseout(mouseHoverFalse);$('.countryData li .button.multi').click(showCountryLanguagePopUp);function showCountryLanguagePopUp(){if($(this).parents('ul').find('.languages.mobile').length>0){var isClosed=$(this).parents('ul').find('.languages.mobile').is(':hidden');resetCountryLanguagePopUp();if(isClosed){if($(this).hasClass('multi')&&$(this).parents('ul').next('.countryData').length<=0){$(this).parents('.countryColumns').append('<ul style="background-position:0 30px" class="countryData temp"></ul>')}
$(this).parents('ul').find('.languages.mobile').show();$(this).parents('ul').find('.button.multi').addClass('active');}}
return false;}
function resetCountryLanguagePopUp(){$('.countryData.temp').remove();$('.languages.mobile').hide();$('.button.multi').removeClass('active');}
function showCountryLanguageSelector(){displayCountryLanguageSelector=true;isMouseOnHover=true;if($('.country-language-selector .dropdown-selector').is(":visible")){$('.drop-button img').attr('src','/PublishingImages/Accenture/FlagsNew/countrylangselector_dropdown.png');$('.country-language-selector').removeClass('active');resetCountryLanguagePopUp();$('.country-language-selector .dropdown-selector').hide();}
else{$('.drop-button img').attr('src','/PublishingImages/Accenture/FlagsNew/countrylangselector_close.png');$('.country-language-selector').addClass('active');$('.country-language-selector .dropdown-selector').show();}
if(/msie|MSIE 6/.test(navigator.userAgent)){$(document.frames.ddframe.document.body).css('border',"1px solid gray");}}
function mouseHoverTrue(){isMouseOnHover=true;}
function mouseHoverFalse(){isMouseOnHover=false;}
$(document).click(function(){if((displayCountryLanguageSelector==true)&&(isMouseOnHover==false)){$('.drop-button img').attr('src','/PublishingImages/Accenture/FlagsNew/countrylangselector_dropdown.png');$('.country-language-selector').removeClass('active');resetCountryLanguagePopUp();$('.country-language-selector .dropdown-selector').hide();displayCountryLanguageSelector=false;}});function isIE7(){if(typeof(navigator.userAgent.match(/msie/i))!='undefined'&&typeof(navigator.userAgent)!='undefined'&&navigator.userAgent.match(/msie/i)&&clientBrowser.browser.ie==7){return true;}
return false;}
$(document).ready(function(){if(isIE7()){$('.country-language-selector .dropdown-selector .countryColumns .countryData .button').click(function(){if($(this).parents('ul').find('.language.selectionpanel').is(':hidden')){$(this).parents('ul').find('.button').removeClass('ie7open');}else{$(this).parents('ul').find('.button').addClass('ie7open');}});$('.LoginNavigation .pipebar').css('display','inline-block');$('.CarPipebar').css('display','inline-block');}
if(clientBrowser.browser.safari!=0&&!window.chrome){$('.country-language-selector .dropdown-selector .countryColumns .countryData .button.multi').hover(function(){$(this).css('text-decoration','none');});}
if(isTabletBrowser()){$('.country-language-selector').click(function(){if($('.country-language-selector .dropdown-selector').is(':hidden')){$(this).css('background-color','transparent');}else{$(this).css('background-color','');}});$('.country-language-selector  .dropdown-selector .countryColumns .countryData').hover(function(){if($(this).find('li a span').hasClass('clicked')){$(this).find('li a span').removeClass('clicked');}else{$(this).find('li a span').addClass('clicked');}});$('.country-language-selector .dropdown-selector .countryColumns .countryData .button.multi').click(function(){if($(this).hasClass('active')){$(this).removeClass('nonactive');}else{$(this).addClass('nonactive');$(this).css('text-decoration','none');}});}
if(/msie|MSIE 6/.test(navigator.userAgent)){$('.country-language-selector .dropdown-selector').css('padding',"0px");var countryLangSelector=$('.country-language-selector .dropdown-selector');var countryLangHeight=$('.country-language-selector .dropdown-selector').height();var countryLangWidth=$('.country-language-selector .dropdown-selector').width();for(c=0;c<countryLangSelector.length;c++){countryLangSelector[c].innerHTML=('<iframe id="ddframe" src="/_layouts/blank.htm" scrolling="no" frameborder="1"></iframe>'+countryLangSelector[c].innerHTML);var frameStyle=countryLangSelector[c].childNodes[0];countryLangHeight=countryLangHeight+10;countryLangWidth=countryLangWidth+1;frameStyle.style.height=countryLangHeight+"px";frameStyle.style.width=countryLangWidth+"px";}
$('.country-language-selector .dropdown-selector').css('height',countryLangHeight+"px");$('.country-language-selector .dropdown-selector').css('border',"none");$('.country-language-selector .dropdown-selector').css('margin-left',"-"+countryLangWidth+"px");$('.country-language-selector .dropdown-selector .countryColumns').css('margin',"-"+countryLangHeight+"px 0px 0px 14px");$(".banner .nav-wrapper .primary-nav .drop-down").prepend("<iframe id = 'iframe-sub-wrapper'></iframe>");$(".banner .nav-wrapper .primary-nav .drop-down .spacer").css({'position':'absolute'});$(".banner .nav-wrapper .primary-nav .drop-down .sub-wrapper").css({'position':'absolute','margin':' 29px auto 0'});}});if(/msie|MSIE 6/.test(navigator.userAgent)){$("img[src$='.png'], img[src$='.jpg']").each(function(){if(!this.complete){this.onload=function(){SetImageTransparencyInIE6(this)};}else{SetImageTransparencyInIE6(this);}});if(($('.outlook-page').length)&&($('.outlook-page .banner').find('img.hpb-logo').length)){$('.outlook-page .main-contents').css('margin-top','-35px');$('.outlook-page .banner img.hpb-logo').css('height','25px');$('.outlook-page .header-sec .primary-nav .outlookContainer').css('margin','-31px auto 0px');}}
setLeftCoordinateLoginNavigationMenu();if($('.HomepageFeaturedSection').text()!=""){if($('.breadcrumbs').text()==""||$('.breadcrumbs').text().replace(/\s/g,"")==""){$('.dlp-hidden').css("display","none");}}
if((/msie|MSIE 7/.test(navigator.userAgent))&&(typeof document.documentMode==='undefined')){if($('.page .main-contents').css('position')=='relative'){$('.page, .bannersearch').css('position','relative');$('.contactUsTop').css('letter-spacing','0');$('.search-localize').css({'top':'0px','left':'0px'});$('.page .noindex #skipfooterlinkholder').css({'position':'absolute','top':'0px','width':'1px','height':'1px','overflow':'hidden'});}}
if(!(url.indexOf("/landing-pages/")>-1||url.indexOf("/microsites/")>-1||url.indexOf("careers.")>-1||url.indexOf("careers-")>-1)){$('div.closeSubMenuContainer').wrap('<div class="bottom" />');$('div.closeSubMenuContainer').eq(0).clone(true,true).prependTo(".drop-down-tablet.sub-wrapper");}
if(TnT_CurrentLayout=="AcnComArticleExecutiveSummary"||TnT_CurrentLayout=="AcnComArticleFullView"||TnT_CurrentLayout=="CareersJobPostingLayout"||TnT_CurrentLayout=="comOutlookJournalArticlePage"||TnT_CurrentLayout=="CareersMeetOurPeopleLayout"||TnT_CurrentLayout=="CareersWorkingAtAccentureLayout"||TnT_CurrentLayout=="CareersArticlePageLayout"||TnT_CurrentLayout=="Person"){var articleTitle=$('h1').text();if(typeof addthis!=='undefined'&&articleTitle!=""){addthis.update('share','title',articleTitle);}}});if(/msie|MSIE 6/.test(navigator.userAgent)){try{document.execCommand('BackgroundImageCache',false,true);}
catch(e){}}
function setLeftCoordinateLoginNavigationMenu(){var loginMenu=null;var loginNavMenu=null;if($('.OutlookLoginMenuButton').length>0){loginNavMenu=$('.OutlookLoginNavigationMenu');loginMenu=$('.OutlookLoginMenuButton input');var OutlooklistItemHeight=22;var newWidth=0;var currentWidth;if(loginMenu.length){if(/msie|MSIE 8/.test(navigator.userAgent)){if($('div').not('communities-bannersearch')){$('.OutlookLoginNavigationMenu ul li').each(function(){currentWidth=$(this).width();if($(this).height()>OutlooklistItemHeight){$('.OutlookLoginNavigationMenu ul li').css('white-space','nowrap');currentWidth=$(this).width();}
if(currentWidth>newWidth)
newWidth=currentWidth;$('.OutlookLoginNavigationMenu ul li').css('white-space','normal');});if(newWidth>0)
$('.OutlookLoginNavigationMenu').css('width',newWidth+'px');}}}}
else if($('.LoginNavigationMenu').length>0){loginNavMenu=$('.LoginNavigationMenu');loginMenu=$('.LoginMenuButton input');var firstA=loginNavMenu.find('ul li:first').find('a:first');var newWidth=0;var currentWidth;if(/msie|MSIE 7/.test(navigator.userAgent)){loginNavMenu.css("left","auto");setTimeout(function(){$('.LoginNavigationMenu ul li').each(function(){$('.LoginNavigationMenu ul li').css('white-space','nowrap');$('.LoginNavigationMenu ul li').find('a').css('padding-right',18+'px');currentWidth=$(this).width();if(currentWidth>newWidth){newWidth=currentWidth;}});if(newWidth>0){var oWidth=parseInt($('.LoginNavigationMenu').width())-(parseInt(firstA.css('margin-left'))+parseInt(firstA.css('margin-right'))+parseInt(firstA.css('padding-left'))+parseInt(firstA.css('padding-right')));$('.LoginNavigationMenu ul li').find('a').css("cssText",";width:"+oWidth+"px !important");}},10);}
if(!(/msie|MSIE 7/.test(navigator.userAgent))){if(firstA.length>0){var oWidth=parseInt($('.LoginNavigationMenu').width())-(parseInt(firstA.css('margin-left'))+parseInt(firstA.css('margin-right'))+parseInt(firstA.css('padding-left'))+parseInt(firstA.css('padding-right')));$('.LoginNavigationMenu ul li').find('a').css('width',oWidth+'px');}}}
if(loginMenu!=null&&loginMenu.length>0){var loginMenuButtonRight=loginMenu.position().left+loginMenu.outerWidth();var loginNavigationMenuLeft=parseInt(loginMenuButtonRight-loginNavMenu.outerWidth());var loginNavMenuTopPos=parseInt(loginMenu.position().top)-1;loginNavMenu.css("left",loginNavigationMenuLeft+'px');loginNavMenu.css("top",loginNavMenuTopPos+'px');}}
function selectDropDownIEbehavior(){if(!$.browser.msie)
return;var expand=function(){var width=$(this).css("width");if(width=="auto")
return;$(this).data("origWidth",width).css("width","auto")};var contract=function(){var width=$(this).css("width");if(width!="auto")
return;var origWidth=$(this).data("origWidth");if(typeof(origWidth)==="undefined")
return;$(this).css("width",origWidth).data("origWidth",width);};$("select").each(function(index){var width=$(this).css("width");var span='<span style="padding: 2px; width:'+width+'; overflow:hidden; float:left;">';$(this).wrap(span);$(this).mousedown(expand).blur(contract).change(contract);});}
function SetImageTransparencyInIE6(transparentImage){if($(transparentImage).width()>0&&$(transparentImage).height()>0){var src=transparentImage.src;if(!transparentImage.style.width){transparentImage.style.width=$(transparentImage).width();}
if(!transparentImage.style.height){transparentImage.style.height=$(transparentImage).height();}
transparentImage.onload=function(){};transparentImage.src='/PublishingImages/blank.gif';transparentImage.runtimeStyle.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+src+"',sizingMethod='scale')";}}
function PopUpWindow(refer){$(document).ready(function(){var height=(screen.height*0.70);var width=(screen.width*0.80);var top=((screen.height/2)-(height/2));var left=((screen.width/2)-(width/2));var openWin=self.open(refer,"popupwindow","toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, copyhistory=no, width="+width+", height="+height+", top="+top+", left="+left);});}
function PrintContent(){var winprint;var strPageContentHtml;var strFooterHtml;var strOption;var strPrintHtml;var strTitle=document.title;var pageUrl=document.location.href;var limeLightEmbeddedPlayer=$('.LimelightEmbeddedPlayer');var limeLightEmbeddedPlayerParentDiv=limeLightEmbeddedPlayer.closest("div");if((limeLightEmbeddedPlayerParentDiv.css("border")=="solid")||(($(limeLightEmbeddedPlayerParentDiv).css("border-right-style")=="solid")&&($(limeLightEmbeddedPlayerParentDiv).css("border-left-style")=="solid")&&($(limeLightEmbeddedPlayerParentDiv).css("border-top-style")=="solid")&&($(limeLightEmbeddedPlayerParentDiv).css("border-bottom-style")=="solid")))
{$(limeLightEmbeddedPlayerParentDiv).addClass("videoBorder");}
strOptions="toolbar=0,location=0,directories=0,menubar=0,status=0,resizable=1,scrollbars=1,";strOptions+="width=760,height=560,left=100,top=25";strPageContentHtml=$('.main-contents').html();var fbdiv=$('#fbLike').html();strPageContentHtml=strPageContentHtml.replace(fbdiv,"");strPageContentHtml=strPageContentHtml.replace(/<script(.|\s)*?\/script>/gi,"");strPageContentHtml=strPageContentHtml.replace(/<object(.|\s)*?\/object>/gi,"");var footer=$('.footer');if(footer.length>1){strFooterHtml='<div class="footer">'+$(footer[1]).html()+'</div>';}else{strFooterHtml='<div class="footer">'+$(footer).html()+'</div>';}
strPrintHtml='<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">';strPrintHtml+='<html><head>';strPrintHtml+='<title>'+strTitle+'</title>';strPrintHtml+=ApplyCSS();strPrintHtml+='</head><body onload="print()">';strPrintHtml+='<div class="print-logo-container">';strPrintHtml+='<img class="logo" src="/PublishingImages/AccSignature_148px_gray.jpg"/></div>';strPrintHtml+='<div id="popup-content" class="popup-content">';strPrintHtml+=strPageContentHtml;strPrintHtml+='</div>';strPrintHtml+='<div class="print-footer-section">';strPrintHtml+='<div class="print-url-container fsize-c">';strPrintHtml+='<div class="print-url-lbl"><strong>Find this article at:</strong></div>';strPrintHtml+='<a class="print-url-link" href="'+pageUrl+'" target="_blank">';strPrintHtml+=pageUrl+'</a></div>';strPrintHtml+=strFooterHtml;strPrintHtml+='</div></body></html>';winprint=window.open(window.location.href,"",strOptions);winprint.document.open();winprint.document.write(strPrintHtml);winprint.document.close();var linksCollection=winprint.document.getElementById('popup-content').getElementsByTagName('a');for(var index=0;index<linksCollection.length;index++){$(linksCollection[index]).removeAttr('href');}}
function ApplyCSS(){var strCssHtml;var strCurrentSite=document.location.hostname.toLowerCase();strCssHtml='<link type="text/css" rel="stylesheet" ';if(strCurrentSite.indexOf("careers")>-1)
strCssHtml+='href="/Style%20Library/Accenture/Core%20Styles/zzz_careersstyle-core.css"/>';else
strCssHtml+='href="/Style%20Library/Accenture/Core%20Styles/zzz_style-core.css"/>';strCssHtml+='<link type="text/css" rel="stylesheet" ';strCssHtml+='href="/Style%20Library/Accenture/Core%20Styles/Media_Print_Style.css"/>';var currAddress=window.location.pathname;if(currAddress.search(/network/i)==1)
{strCssHtml+='<link type="text/css" rel="stylesheet" ';strCssHtml+='href="/Style%20Library/Accenture/Core%20Styles/Media_Print_Style_Network.css"/>';}
var fileNameIE6="Style_IE6";var fileNameIE7="Style_IE7";var fileNameIE8="Style_IE8";if(strCurrentSite.indexOf("careers")>-1){fileNameIE6+="-Careers";fileNameIE7+="-Careers";fileNameIE8+="-Careers";}
strCssHtml+='<!--[if IE 6]>';strCssHtml+='<link type="text/css" rel="stylesheet" href="/Style Library/Accenture/Core Styles/'+fileNameIE6+'.css"></link>';strCssHtml+='<![endif]-->';strCssHtml+='<!--[if IE 7]>';strCssHtml+='<link type="text/css" rel="stylesheet" href="/Style Library/Accenture/Core Styles/'+fileNameIE7+'.css"></link>';strCssHtml+='<![endif]-->';strCssHtml+='<!--[if IE 8]>';strCssHtml+='<link type="text/css" rel="stylesheet" href="/Style Library/Accenture/Core Styles/'+fileNameIE8+'.css"></link>';strCssHtml+='<![endif]-->';return strCssHtml;}<!--
var _UHcookieSubstring;var _UHcurrentPage=unescape(document.location.href.toLowerCase())
var _UHCookieKey="URLHistory";var _UHLinks=new Array();var _UHLinkDefinitions=new Array();var _UHArray=new Array();var _UHMaxLength=6;var _checker=-1;var _ERUrlString;var _ERCookiekey="External_ReferrerURL";var _ExternalReferrerUrl=document.referrer;var _ReferrerUrl=document.referrer;var _RCookiekey="ReferrerURL";var _expireDate=new Date();_expireDate.setHours(_expireDate.getHours()+24);_UHLinkDefinitions=GetUHList();UHCreateLinkArray()
UHMatchPage();if(top.location!=self.location)
{top.location=self.location}
if(_ExternalReferrerUrl.length>0)
{SetExternalReferrerUrlCookie();}
SetReferrerUrlCookie();function UHGetCookieVal(offset)
{var endstr=unescape(document.cookie.indexOf(";",offset));if(endstr==_checker)
{endstr=document.cookie.length;}
return unescape(document.cookie.substring(offset,endstr));}
function UHGetCookie(name)
{var _argument=name;var _argumentLength=_argument.length;var _cookieLength=document.cookie.length;var _cookieIndex=0;while(_cookieIndex<_cookieLength)
{var _endingIndex=_cookieIndex+_argumentLength;if(document.cookie.substring(_cookieIndex,_endingIndex)==_argument)
{return UHGetCookieVal(_endingIndex);break;}
_cookieIndex++;}
return"";}
function GetUHList()
{var extRef=unescape(_ExternalReferrerUrl);_UHcookieSubstring=unescape(UHGetCookie(_UHCookieKey+'='));if(extRef!="")
{if(extRef.toLowerCase().indexOf("accenture.com")<0)
{if(extRef.indexOf("?")>0)
{extRef=extRef.substring(0,extRef.indexOf("?"));}
_UHcookieSubstring=extRef+" "+"|"+_UHcookieSubstring}}
extRef="";_UHArray=_UHcookieSubstring.split("|");return _UHArray;}
function UHMatchPage()
{var _cookie="";var _match;var _end=0;_match=_UHcookieSubstring.indexOf(_UHcurrentPage+"|");preUrl=UHUrlChecker(_UHcookieSubstring)
curUrl=UHUrlChecker(_UHcurrentPage)
if($('#MSOSPWebPartManager_DisplayModeName').val()!='Browse'||preUrl==curUrl){return}
if(_UHLinks.length!=_UHMaxLength)
{if(document.cookie.length>2047)
{_end=_UHcookieSubstring.lastIndexOf("|");_UHcookieSubstring=_UHcookieSubstring.substring(0,_end);_end=_UHcookieSubstring.lastIndexOf("|");_UHcookieSubstring=_UHcookieSubstring.substring(0,_end+1);_cookie=_UHcurrentPage+"|"+_UHcookieSubstring;}
_cookie=_UHcurrentPage+"|"+_UHcookieSubstring;}
else
{_end=_UHcookieSubstring.lastIndexOf("|");_UHcookieSubstring=_UHcookieSubstring.substring(0,_end);_end=_UHcookieSubstring.lastIndexOf("|");_UHcookieSubstring=_UHcookieSubstring.substring(0,_end+1);_cookie=_UHcurrentPage+"|"+_UHcookieSubstring;}
UHUpdateCookie(_cookie);_cookie="";_match=0;_end=0;}
function UHUpdateCookie(value)
{var _updatedCookie=_UHCookieKey+"="+escape(value)+"; path=/"+"; domain=.accenture.com";document.cookie=_updatedCookie;_updatedCookie="";}
function UHCreateLinkArray()
{for(var _counter=0;_counter<_UHLinkDefinitions.length-1;++_counter)
{var _link=_UHLinkDefinitions[_counter];_UHLinks[_counter]=_link;}
return _UHLinks;}
function UHUrlChecker(Url)
{var cookieArray=new Array();var pageUrl;cookieArray=Url.split("|");if(cookieArray!=null)
{pageUrl=cookieArray[0];}
else
{pageUrl=Url}
pageUrl=pageUrl.replace("http://","");pageUrl=pageUrl.replace("https://","");pageUrl=pageUrl.substring(pageUrl.indexOf("/"));return(pageUrl)}
function SetExternalReferrerUrlCookie()
{_ERUrlString=unescape(_ExternalReferrerUrl);if(_ERUrlString.indexOf("?")>0)
{_ERUrlString=_ERUrlString.substring(0,_ERUrlString.indexOf("?"));}
if(_ERUrlString.toLowerCase().indexOf("accenture.com")<0)
{var _newCookie=_ERCookiekey+"="+unescape(_ExternalReferrerUrl)+"; path=/"+"; domain=.accenture.com";document.cookie=_newCookie;_newCookie="";}}
function SetReferrerUrlCookie()
{var referrer="";var prevUrl=_ReferrerUrl;var curUrl=document.location.pathname;var hostName=document.location.hostname;var offset=prevUrl.indexOf(hostName)+hostName.length;if(offset<0){offset=0;}
var qStringIndex=prevUrl.indexOf("?");if(qStringIndex<0){qStringIndex=prevUrl.length;}
prevUrl=prevUrl.substring(offset,qStringIndex);var portOffset=prevUrl.indexOf("/");if(portOffset>0){prevUrl=prevUrl.substring(portOffset);}
if(prevUrl!=curUrl){if($('#MSOSPWebPartManager_DisplayModeName').val()=='Browse'){if(_ReferrerUrl.length>0){referrer=_ReferrerUrl;}
else if(_UHLinks.length>0){referrer=_UHLinks[0];}
var _newCookie2=_RCookiekey+"="+unescape(referrer)+"; path=/"+"; domain=.accenture.com";document.cookie=_newCookie2;_newCookie2="";}}}
_UHLinks=null;_UHcurrentPage="";_UHCookieKey="";_ERCookieKey="";_RCookiekey="";_ExternalReferrerUrl="";_ReferrerUrl="";var display=true;if(typeof(TnT_CurrentLayout)!="undefined"){if(TnT_CurrentLayout=="Homepage"){SetLocationLoginControl();}}
function SetLocationLoginControl(){if($(".user-status").html()!=null){$(".user-status").css('width','948px');}
if($(".UserControlLoginNote").html()!=null){$(".UserControlLoginNote").css('float','none');$(".UserControlLoginNote").css('display','inline');$(".UserControlLoginNote").css('vertical-align','top');}
if($(".LoginName").html()!=null){$(".LoginName").css('vertical-align','top');}
if($(".LoginMenuButton").html()!=null){$(".LoginMenuButton").css('float','none');$(".LoginMenuButton").css('display','inline');$(".LoginMenuButton").css('vertical-align','top');}
if($(".LoginNote").html()!=null){$(".LoginNote").css('float','none');$(".LoginNote").css('display','inline');$(".LoginNote").css('vertical-align','top');$(".LoginNote a").css('vertical-align','top');$(".LoginNote .divOrLiteral").css('vertical-align','top');}
if($(".OutlookLoginMenuButton").html()!=null){$(".OutlookLoginMenuButton").css('float','none');$(".OutlookLoginMenuButton").css('display','inline');}
if($(".OutlookLoginNavigationMenu").html()!=null){$(".OutlookLoginNavigationMenu").css('float','none');}}
function ChangeLoginButton(){if((__hasOpenMenuDropdown)&&(TnT_CurrentLayout=="Homepage")){$(".BtnToggleNavigation").css("background-position","0px -56px");}else{$(".BtnToggleNavigation").css("background-position","0px 0px");}}
function ToggleNavigation(ScopeDiv,ImageButton){display=true;var url=window.location.href.toString().toLowerCase();if(document.getElementById(ScopeDiv).style.display==""){document.getElementById(ScopeDiv).style.display="none";if(url.indexOf("/network/")>0){$(".BtnToggleNavigation").css("background-position","0px 56px");}else{ChangeLoginButton();$('.banner .nav-wrapper .primary-nav .drop-down ul').removeClass('priNavDisabled');$('.banner .nav-wrapper .primary-nav .drop-down ul a').unbind();}}else{document.getElementById(ScopeDiv).style.display="";if(url.indexOf("/network/")>0){$(".BtnToggleNavigation").css("background-position","0px 28px");}else{$(".BtnToggleNavigation").css("background-position","0px -84px");$('.banner .nav-wrapper .primary-nav .drop-down ul').addClass('priNavDisabled');$('.banner .nav-wrapper .primary-nav .drop-down ul a').click(function(event){if(!event.isDefaultPrevented()){event.preventDefault();}});}}
return false;}
function OutlookToggleNavigation(ScopeDiv,ImageButton){display=true;if(document.getElementById(ScopeDiv).style.display==""){document.getElementById(ScopeDiv).style.display="none";document.getElementById(ImageButton).src="/PublishingImages/Accenture/arrow.png";}
else{document.getElementById(ScopeDiv).style.display="";document.getElementById(ImageButton).src="/PublishingImages/Accenture/arrow.png";}
return false;}
$(document).ready(function(){$("#LogoutPanel .LoginNote a").click(function(){var acnCookie=$.cookie('_ACCENTURE_COM_');if(acnCookie!=null&&acnCookie!=""){if(acnCookie.indexOf("&")>-1){var updatedAcnCookie=acnCookie.substr(0,acnCookie.indexOf("&"));$.cookie('_ACCENTURE_COM_',updatedAcnCookie,{expires:365,domain:'accenture.com',path:'/'});}}});});var isClose=false;var origVal="";var rowHighlighted;var pos=0;var searchBox;var searchSuggestion=false;var divID="";var chosenRow="";var timeOut;var isDropdownOver="";var MicrositesSearch=false;var timer;var display=true;var tabKey=false;function SearchBoxOnFocus(searchTextBox){if(searchSuggestion==false)
searchTextBox.value="";}
function Detect(searchTextBox,e){var KeyID=e.keyCode;var backspaceKey=8;var enterKey=13;var escapeKey=27;var arrowUpKey=38;var rightKey=39;var arrowDownKey=40;var printScreenKey=44;var deleteKey=46;searchBox=searchTextBox;switch(KeyID){case printScreenKey:break;case enterKey:Collapse(searchTextBox);break;case backspaceKey:{WriteCookieValue("");origVal=searchTextBox.value;if(isClose==false){clearTimeout(timeOut);timeOut=setTimeout("Expand('false')",200)}
if(Ltrim(searchTextBox.value).length==0)
isClose=false;pos=0;}
break;case deleteKey:{origVal=searchTextBox.value;if(isClose==false){clearTimeout(timeOut);timeOut=setTimeout("Expand('false')",200)}
if(Ltrim(searchTextBox.value).length==0)
isClose=false;pos=0;}
break;case escapeKey:{if(document.getElementById("row1")!=null)
Collapse(searchTextBox);searchTextBox.value=origVal;}
break;case rightKey:OnRightKey(rowHighlighted);break;case arrowDownKey:{WriteCookieValue("s");OnDownKey(searchTextBox);}
break;case arrowUpKey:{WriteCookieValue("s");OnUpKey(searchTextBox);}
break;default:{WriteCookieValue("");origVal=searchTextBox.value;if(isClose==false){clearTimeout(timeOut);timeOut=setTimeout("Expand('false')",250)}}}}
function WriteCookieValue(val){if(typeof window.s!=='undefined'){window.s.c_w('SC_SEARCH',val,0);}}
function Expand(displaymax){if(searchBox!=undefined){if(isClose==false){divID=GetSearchSuggestDiv(searchBox);var state=document.getElementById(divID);var width=SetSearchSuggestWidth(searchBox);if((Ltrim(searchBox.value).length)>0){origVal=Ltrim(searchBox.value);if(window.ActiveXObject){if(displaymax=="true")
state.innerHTML=DisplayResult(origVal,width,"true");else
state.innerHTML=DisplayResult(origVal,width,"false");}
else if(document.implementation&&document.implementation.createDocument){if(displaymax=="true")
state.appendChild(DisplayResult(origVal,width,"true"));else
state.appendChild(DisplayResult(origVal,width,"false"));}
if(document.getElementById("row1")==null){Collapse(searchBox);}
else if(document.getElementById("row1")!=null){state.className="expand";if(/msie|MSIE 6/.test(navigator.userAgent)){SetSearchSuggestWidthIE6(displaymax);}
var documentMode=document.documentMode;if((documentMode==7)||((/msie|MSIE 7/.test(navigator.userAgent))&&(!/Trident/.test(navigator.userAgent))&&(typeof documentMode==='undefined'))){if(displaymax=="true"){$('#searchSuggestBanner div .tableSearchSuggest').attr('style','margin-right:0px !important');}}}}
else{Collapse(searchBox);isClose=false;}}}}
function SetSearchSuggestWidthIE6(displaymax){var width=$('#searchSuggestBanner div .tableSearchSuggest').width();var height=$('#searchSuggestBanner div .tableSearchSuggest').height();$('#searchSuggestBanner div').css('overflow-x','hidden');if(displaymax=="true"){$('#searchSuggestBanner div').css('overflow-y','scroll');$('#searchSuggestBanner').width(width+20);$('#searchSuggestBanner div').height('194px');}
else{$('#searchSuggestBanner').width(width);$('#searchSuggestBanner div').css('overflow-y','hidden');$('#searchSuggestBanner div').height(height);}}
function Collapse(searchTextBox){divID=GetSearchSuggestDiv(searchTextBox);var state=document.getElementById(divID);state.className="collapse";state.innerHTML="";searchSuggestion=true;searchTextBox.focus();}
function DisplayResult(input,width,displaymax){var str=input;var firstChar=String(str).substring(0,1);input=input.replace(",","&#44");input=input.replace(";","&#59");var param="width,"+width+";rawinput,"+input;if(g_basicSearchSuggestionLabel!=undefined)
param+=";suggestionsLabel,"+g_basicSearchSuggestionLabel;if(g_basicSearchCloseLabel!=undefined)
param+=";closeLabel,"+g_basicSearchCloseLabel.toLowerCase();if(IsNumeric(firstChar)){var xmlPath=xmlFilePath+"Numeric.xml";}
else{var xmlPath=xmlFilePath+firstChar+".xml";}
if(displaymax=="true"){param+=";maxdisplay,1000";}
if(g_basicSearchSeeAllLabel!=undefined){param+=";SeeAllLabel,"+g_basicSearchSeeAllLabel;}
var resultSuggestions=xsltTransform(xmlPath,xslFilePath,param);Collapse(searchBox);return(resultSuggestions);}
function OnRightKey(row){Expand(searchBox);Dehighlight(row);pos=0;}
function OnUpKey(searchTextBox){if(document.getElementById("row1")!=null){var row=document.getElementById('row'+pos);if(pos==0){origVal=searchTextBox.value;pos=document.getElementById('searchSuggest').rows.length-1;}
else{Dehighlight(row);pos--}
if(pos==0){searchTextBox.value=origVal;chosenRow="";}
else{var data=document.getElementById('data'+pos);row=document.getElementById('row'+pos)
Highlight(row);if(window.ActiveXObject)
searchTextBox.value=data.innerText;else if(document.implementation&&document.implementation.createDocument)
searchTextBox.value=data.textContent;chosenRow=searchTextBox.value;}}}
function OnDownKey(searchTextBox){if(document.getElementById("row1")!=null){var row=document.getElementById('row'+pos);if((pos==0)&&(origVal.length!=0))
origVal=searchTextBox.value;else
Dehighlight(row);if(pos!=(document.getElementById('searchSuggest').rows.length-1))
pos++;else if(pos>=(document.getElementById('searchSuggest').rows.length-1))
pos=0;var data=document.getElementById('data'+pos);if(pos==0){searchTextBox.value=origVal;chosenRow="";}
else{row=document.getElementById('row'+pos)
Highlight(row);if(window.ActiveXObject)
searchTextBox.value=data.innerText;else if(document.implementation&&document.implementation.createDocument)
searchTextBox.value=data.textContent;chosenRow=searchTextBox.value;}}}
function OnBlurSearchTextBox(searchTextBox){var innerTextVar;if(window.ActiveXObject)
innerTextVar=divID.InnerText;else if(document.implementation&&document.implementation.createDocument)
innerTextVar=divID.textContent;if(innerTextVar=="")
Collapse(searchTextBox);divID=GetSearchSuggestDiv(searchTextBox);var state=document.getElementById(divID);if(state.innerHTML!=""){if(chosenRow==""){searchTextBox.value=origVal;}
else if(chosenRow=="CloseLink"){searchTextBox.focus();searchTextBox.value=origVal;isClose=true;isDropdownOver="";}
else if(chosenRow=="more"){Expand("true");setTimeout(function(){searchTextBox.focus();},10)
isDropdownOver="";}
else{searchTextBox.focus();searchTextBox.value=chosenRow;isDropdownOver="";WriteCookieValue("s");if(!tabKey){$("input[id$='SearchBox_BtnSearch']").click();}}}
if(chosenRow!="more"&&isDropdownOver!="true"){state.className="collapse";state.innerHTML="";searchSuggestion=true;chosenRow="";}
if(isDropdownOver=="true"){setTimeout(function(){searchTextBox.focus();},10);}}
function SuggestMouseOut(){chosenRow="";}
function SuggestMouseOver(row){rowHighlighted=document.getElementById("row"+pos);if(rowHighlighted!=undefined)
Dehighlight(rowHighlighted);Highlight(row);pos=row.id.replace("row","");if(window.ActiveXObject)
chosenRow=document.getElementById("data"+pos).innerText;else if(document.implementation&&document.implementation.createDocument)
chosenRow=document.getElementById("data"+pos).textContent;}
function Highlight(row){row.className="highlight";if(row.id=="row1")
document.getElementById("suggestions").className="suggestHighlight";rowHighlighted=row;}
function Dehighlight(row){if(document.getElementById("suggestions")!=null){document.getElementById("suggestions").className="suggestionsText"
row.className="dehighlight";rowHighlighted=row;}}
function SuggestClosed(row){Collapse(searchBox);isClose=true;}
function GetSearchSuggestDiv(searchTextBox){return("searchSuggestBanner");}
function SetSearchSuggestWidth(searchTextBox){if(Ltrim(searchTextBox.id)=="SiteSearchControlStandard_txtBasicSearch")
return("240px");else
return("180px");}
function IsNumeric(numstr){var mystring=numstr;var IsNumber=false;if((mystring.match(/^\d+$/))||(mystring.match(/^\W+$/)))
IsNumber=true;return IsNumber;}
function CloseSuggestOnKeyUp(searchTextBox,event){if(event.keyCode==8||event.keyCode==46){if(Ltrim(searchTextBox.value).length==0){isClose=false;clearTimeout(timeOut);timeOut=setTimeout("Expand('false')",250)}}}
function EnterKeyHandler(event,btn,searchTextBox){var isIE=window.navigator.appName.toLowerCase().indexOf("microsoft")>-1;if(searchTextBox!=undefined){if(event.keyCode==8||event.keyCode==46){if(Ltrim(document.getElementById(searchTextBox).value).length==0){isClose=false;clearTimeout(timeOut);timeOut=setTimeout("Expand('false')",250)}}}
if(event.keyCode==13){var btn=document.getElementById(btn);if(isIE==false){event.returnValue=false;event.cancel=true;window.releaseEvents(event.KEYPRESS);if(btn!=null){if(btn.click){btn.click();}
else if((btn.tagName=='A')&&(btn.href.length>0)){window.location=btn.href;}}}
else{event.returnValue=false;event.cancel=true;if(btn!=null){btn.click();}}}
else if(event.keyCode==9){tabKey=true;}
else{tabKey=false;}
return false;}
$(document).ready(function(){$('.SearchScopeMenu a').bind('click',function(){$(".SearchScopeMenu a").removeClass("highlightMenu");$(this).addClass("highlightMenu");$('.SearchScopeMenu').hide();val=$('.SearchScopeMenu input')[this.id].value;$('#<%= hidScope.ClientID %>').val(val);});$(document).click(function(e){setLeftCoordinateLoginNavigationMenu();if(display!=true){$('.SearchScopeMenu').hide();$('.LoginNavigationMenu').hide();$('.OutlookLoginNavigationMenu').hide();$($('.OutlookLoginMenuButton').children()[0]).attr("src","/PublishingImages/Accenture/arrow.png");var url=window.location.href.toString().toLowerCase();if(url.indexOf("/network/")>0){$(".BtnToggleNavigation").css("background-position","0px 56px");}else{ChangeLoginButton();$('.banner .nav-wrapper .primary-nav .drop-down ul').removeClass('priNavDisabled');$('.banner .nav-wrapper .primary-nav .drop-down ul a').unbind();}}
display=false;});$(document).keydown(function(e){var e=(e)?e:((event)?event:null);if(e.keyCode==13){var node=(e.target)?e.target:((e.srcElement)?e.srcElement:null);if(typeof(node)!="undefined"&&node.type=="text"){return false;}}
if($(".SearchScopeMenu")[0]!=undefined)
{if($(".SearchScopeMenu")[0].style.display!="none"){if(e.keyCode==40||e.charCode==40){var scopeCount=$(".SearchScopeMenu a").length;for(i=0;i<scopeCount;i++){if($(".SearchScopeMenu a")[i].className=="highlightMenu"){if(scopeCount>i+1){$(".SearchScopeMenu a").removeClass("highlightMenu");$(".SearchScopeMenu a")[i+1].className="highlightMenu";var val1=$('.SearchScopeMenu input')[i+1].value;$('#<%= hidScope.ClientID %>').val(val1);break;}}}
e.preventDefault();return false}
else if(e.keyCode==38||e.charCode==38){var scopeCount=$(".SearchScopeMenu a").length;for(i=0;i<scopeCount;i++){if($(".SearchScopeMenu a")[i].className=="highlightMenu"){if(i>0){$(".SearchScopeMenu a").removeClass("highlightMenu");$(".SearchScopeMenu a")[i-1].className="highlightMenu";var val2=$('.SearchScopeMenu input')[i-1].value;$('#<%= hidScope.ClientID %>').val(val2);break;}}}
e.preventDefault();return false}}}});SetBannerSearchProp();});function ToggleScopeMenu(ScopeDiv){display=true;if(document.getElementById(ScopeDiv).style.display==""){document.getElementById(ScopeDiv).style.display="none";}
else{document.getElementById(ScopeDiv).style.display="";}
return false;}
function SetBannerSearchProp(){if(/Windows NT 6/.test(navigator.userAgent)&&typeof clientBrowser!='undefined'){$(".search-localize .SearchBox_BtnSearch").css("margin-left","0px");}}
$(document).ready(function(){$('.main-contents').find('img').each(function(i){var altText=$(this).attr('alt');$(this).attr('title',altText);});});var lastXMLloaded='';var lastXSLloaded='';var xml;var xsl;function xsltTransform(xmlPath,xslPath,parameter){if(lastXMLloaded!=xmlPath){xml=loadXMLDoc(xmlPath);lastXMLloaded=xmlPath;}
if(lastXSLloaded!=xslPath){xsl=loadXSLDoc(xslPath);lastXSLloaded=xslPath;}
var param=parameter.split(";");var count=param.length;if(window.ActiveXObject){var template=new ActiveXObject("MSXML2.XSLTemplate");template.stylesheet=xsl.documentElement;var xsltProcessor=template.createProcessor();xsltProcessor.input=xml;for(i=0;i<=count-1;i++){var paramKeyValue=param[i].split(",");xsltProcessor.addParameter(paramKeyValue[0],paramKeyValue[1]);}
xsltProcessor.transform();var result=xsltProcessor.output;return result;}
else if(document.implementation&&document.implementation.createDocument){xsltProcessor=new XSLTProcessor();try{xsltProcessor.importStylesheet(xsl);}
catch(e){}
for(i=0;i<=count-1;i++){var paramKeyValue=param[i].split(",");xsltProcessor.setParameter(null,paramKeyValue[0],paramKeyValue[1]);}
var resultDocument=xsltProcessor.transformToFragment(xml,document);return resultDocument}}
function loadXSLDoc(fname){var xmlDoc;fname=window.location.protocol+"//"+window.location.host+"/"+fname;if(window.ActiveXObject){xmlDoc=new ActiveXObject("MSXML2.FreeThreadedDomDocument");}
else if(document.implementation&&document.implementation.createDocument){xmlDoc=document.implementation.createDocument("","",null);}
else{alert('Your browser cannot handle this script');}
if(xmlDoc&&typeof xmlDoc.load!='undefined'){xmlDoc.async=false;xmlDoc.load(fname);return xmlDoc;}
else{var request=new XMLHttpRequest();request.open("GET",fname,false);request.send("");return request.responseXML;}}
var xmlhttp;function loadXMLDoc(url){xmlhttp=null;if(window.XMLHttpRequest){xmlhttp=new XMLHttpRequest();}
else if(window.ActiveXObject){xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");}
if(xmlhttp!=null){xmlhttp.open("GET",url,false);xmlhttp.send("");return xmlhttp.responseXML;}}
$(document).ready(function(){var priNav=$('.outlook-page .header-sec .primary-nav .outlookContainer ul li.menu');var priNavWidth;for(var ctr=0;ctr<priNav.length;ctr++)
{priNavWidth=priNav.eq(ctr).width()+16;priNav.eq(ctr).find('.menu-outlooktextlink').css({'width':priNavWidth});}
$('.outlook.primary-nav .img-over').hide();$(".outlook.primary-nav .menu").mouseover(function(){$(this).find('.img-out').hide();$(this).find('.img-over').show();if($(this).find('.drop-down .dropdown-item').html()){$(this).find('.drop-down').show();$(this).find('.drop-down').css('margin-top','19px');$(this).find('.menu-outlooktextlink span').css({'color':'white','font-weight':'400'});$(this).find('.menu-outlooktextlink').css({'background-color':'black'});}else{$(this).find('.drop-down').hide();$(this).find('.menu-outlooktextlink span').css({'color':'white','font-weight':'400'});$(this).find('.menu-outlooktextlink').css({'background-color':'black'});}});$(".outlook.primary-nav .menu").mouseout(function(){$(this).find('.img-over').hide();$(this).find('.img-out').show();$(this).find('.drop-down').hide();$(this).find('.menu-outlooktextlink span').css({'color':'black','font-weight':'700'});$(this).find('.menu-outlooktextlink').css({'background-color':'white'});});$('.outlook.primary-nav .drop-down').hide();});var __primaryNavTimer;var __prevDropDownMenu;var __currentDropDownMenu;var __timer;var __timeConstant=150;var __selectedNavNodeOnLoad;var __hasOpenMenuDropdown=false;var __selectedNavNodeParentId;var __tempPrimaryNavMenu=null;var currentLayout;$(document).ready(function(){__selectedNavNodeOnLoad=$(".primary-nav a[currentNode='Yes']:last");__selectedNavNodeParentId=__selectedNavNodeOnLoad.parent().attr('id');if(window.TkCon){if(TkCon.RolledBack){RevertToImageLinks();}else{TkCon.RollbackHandlers.push(RevertToImageLinks);}}
SelectOnLoadNavNode();$('.drop-down').hide();currentLayout=TnT_CurrentLayout;if(TnT_CurrentLayout=="Homepage"&&document.location.href.toLowerCase().indexOf("/network/")<0){$(".page.wide-layout .nav-wrapper .primary-nav .menu .menu-textlink").attr('mouseoverbackground','#fff');$(".closeSubMenu img").attr("src","/PublishingImages/close-button-red.png");}
$(".nav-wrapper .primary-nav .menu").mouseenter(function(){var parentControl=this;__currentDropDownMenu=this;if(__prevDropDownMenu!==undefined&&__prevDropDownMenu!==parentControl){var textLink=$(__prevDropDownMenu).find('.menu-textlink');if($(textLink).hasClass("menu-textlink")){if(textLink.attr('mouseoutbackground')!==undefined){textLink.removeClass('menu-textlink-active');textLink.css({'background-color':textLink.attr('mouseoutbackground')});}else{textLink.addClass('menu-textlink-active');textLink.attr({'mouseoutbackground':$(".menu-textlink-active").css("background-color")});textLink.css({'background-color':textLink.attr('mouseoutbackground')});}}else{$(__currentDropDownMenu).find('.img-out').hide();ShowPriNavImageOver($(__currentDropDownMenu));}}
clearTimeout(__primaryNavTimer);if(!__timer){__timer=setTimeout(function(){OpenDropDownMenu(parentControl);},__timeConstant);}
if($(this).attr('id')!=__selectedNavNodeParentId){DeselectOnLoadNavNode();}});$(".nav-wrapper .primary-nav").mouseleave(function(){setTimeout(function(){SelectOnLoadNavNode();},__timeConstant);});$(".nav-wrapper .primary-nav .menu").mouseleave(function(){__prevDropDownMenu=this;SetDropDownTimeOut(this);$(".nav-wrapper .primary-nav .menu .menu-textlink").removeAttr('style');var textLink=$(this).find('.menu-textlink');if(__prevDropDownMenu!==__currentDropDownMenu){if($(textLink).hasClass("menu-textlink")){textLink.removeClass('menu-textlink-active');if(textLink.attr('mouseoutbackground')!==undefined){textLink.css({'background-color':textLink.attr('mouseoutbackground')});}else{textLink.removeClass('menu-textlink-active');textLink.attr({'mouseoutbackground':$(".menu-textlink").css("background-color")});textLink.css({'background-color':textLink.attr('mouseoutbackground')});}}else{HidePriNavImageOver($(".primary-nav .menu"));$(".primary-nav .menu").find('.img-out').show();}}});$(".nav-wrapper .user-status").mouseenter(function(event){clearTimeout(__primaryNavTimer);if(event.relatedTarget!=null){if(event.relatedTarget.className=="img-over"||event.relatedTarget.className=="spacer"||event.relatedTarget.className=="img-over-homepage"){var prevloc="li[id=\""+event.relatedTarget.parentNode.parentNode.id+"\"]."+event.relatedTarget.parentNode.parentNode.className;var textLink=$(prevloc).find('.menu-textlink');if($(textLink).hasClass("menu-textlink")){if(textLink.attr('mouseoverbackground')!==undefined){textLink.css({'background-color':textLink.attr('mouseoverbackground')});}else{textLink.attr({'mouseoverbackground':$(".menu-textlink-active").css("background-color")});textLink.css({'background-color':textLink.attr('mouseoverbackground')});}}else{$(prevloc).find('.img-out').hide();ShowPriNavImageOver($(prevloc));}
$(prevloc).find('.drop-down').show();}}});$("div[id$=divLogin], .drop-down, .drop-down div.spacer, .sub-wrapper, .hpb-userstatus").mouseenter(function(event){if($(__currentDropDownMenu).find('ul li.column').length>0&&(__hasOpenMenuDropdown)){clearTimeout(__primaryNavTimer);if($(__currentDropDownMenu).find('.menu-textlink').hasClass("menu-textlink")){if(document.location.href.toLowerCase().indexOf("/network/")>-1){var textLink=$(__currentDropDownMenu).find('.menu-textlink');if(textLink.attr('mouseoverbackground')!==undefined){textLink.css({'background-color':textLink.attr('mouseoverbackground')});}else{textLink.attr({'mouseoverbackground':$(".menu-textlink-active").css("background-color")});textLink.css({'background-color':textLink.attr('mouseoverbackground')});}}else if(TnT_CurrentLayout=="Homepage"){$(__currentDropDownMenu).find('.menu-textlink').attr('style','color: #a13 !important ; background-color: #fff;');}else{$(__currentDropDownMenu).find('.menu-textlink').attr('style','color: #fff !important ; background-color: #a13;');}}else{$(__currentDropDownMenu).find('.img-out').hide();ShowPriNavImageOver($(__currentDropDownMenu));}}});$(".user-status, .hpb-userstatus").mouseleave(function(){if($(__currentDropDownMenu).find('ul li.column').length>0&&(__hasOpenMenuDropdown)){var __prevDropDownMenu=$(".nav-wrapper .primary-nav .menu");SetDropDownTimeOut(__prevDropDownMenu);$(".nav-wrapper .primary-nav .menu .menu-textlink").removeAttr('style');var textLink=$(this).find('.menu-textlink');if(__prevDropDownMenu!==__currentDropDownMenu){if($(textLink).hasClass("menu-textlink")){textLink.removeClass('menu-textlink-active');if(textLink.attr('mouseoutbackground')!==undefined){textLink.css({'background-color':textLink.attr('mouseoutbackground')});}else{textLink.removeClass('menu-textlink-active');textLink.attr({'mouseoutbackground':$(".menu-textlink").css("background-color")});textLink.css({'background-color':textLink.attr('mouseoutbackground')});}}else{HidePriNavImageOver($(".primary-nav .menu"));$(".primary-nav .menu").find('.img-out').show();}}}
setTimeout(function(){SelectOnLoadNavNode();},__timeConstant);});$(".nav-wrapper .primary-nav .menu .menu-textlink").click(function(event){if(!event.isDefaultPrevented()&&$(this).attr('href')=="#self"){var parentControl=$(this).parent();__prevDropDownMenu=$(this).parent();if(__prevDropDownMenu!==undefined&&__prevDropDownMenu!==parentControl){$(".nav-wrapper .primary-nav .menu .menu-textlink").removeAttr('style');if($(this).hasClass("menu-textlink")){$(this).css({'background-color':$(this).attr('mouseoverbackground')});if(TnT_CurrentLayout=="Homepage"){$(this).attr('style','color: #a13 !important;background-color:#fff;');}}else{$(this).find('.img-out').hide();ShowPriNavImageOver($(__prevDropDownMenu));}}
clearTimeout(__primaryNavTimer);if(!__timer){__timer=setTimeout(function(){OpenDropDownMenu(parentControl);},__timeConstant);}
if($(this).parent().attr('id')!=__selectedNavNodeParentId){DeselectOnLoadNavNode();}
event.preventDefault();}});$(".nav-wrapper .primary-nav .menu .menu-imagelink").click(function(event){if(typeof event!='undefined'&&!event.isDefaultPrevented()&&$(this).attr('href')=="#self"){var parentControl=$(this).parent();__prevDropDownMenu=$(this).parent();if(__prevDropDownMenu!==undefined&&__prevDropDownMenu!==parentControl){var textLink=$(__prevDropDownMenu).find('.menu-textlink');if($(textLink).hasClass("menu-textlink")){if(textLink.attr('mouseoutbackground')!==undefined){textLink.removeClass('menu-textlink-active');textLink.css({'background-color':textLink.attr('mouseoutbackground')});}else{textLink.addClass('menu-textlink-active');textLink.attr({'mouseoutbackground':$(".menu-textlink-active").css("background-color")});textLink.css({'background-color':textLink.attr('mouseoutbackground')});}}else{$(__prevDropDownMenu).find('.img-out').hide();ShowPriNavImageOver($(__prevDropDownMenu));}}
clearTimeout(__primaryNavTimer);if(!__timer){__timer=setTimeout(function(){OpenDropDownMenu(parentControl);},__timeConstant);}
if($(this).parent().attr('id')!=__selectedNavNodeParentId){DeselectOnLoadNavNode();}
event.preventDefault();}});$(".closeSubMenu").click(function(event){if(!event.isDefaultPrevented()){CloseDropDownMenu(this);$(".nav-wrapper .primary-nav .menu .menu-textlink").attr("style","color:#FFF!important");RemoveTemporaryBackground($(this).parent().parent());SelectOnLoadNavNode();event.preventDefault();}});SetHeaderTextLinkColor();$('.drop-down-tablet li').each(function(){var primNavLiContainer=$(this);var primNavChildNode=primNavLiContainer.find('ul div');var primNavLiEmpty=primNavLiContainer.find('ul.item');if(primNavChildNode.hasClass('colspanNavItem')){primNavLiContainer.removeClass();}
$(primNavLiEmpty).filter(function(){return $.trim($(this).html())=='';}).parent().hide()});});function ShowPriNavImageOver(PriNavImageContainer){if(TnT_CurrentLayout=="Homepage"&&PriNavImageContainer.find('.img-over-homepage').attr('src')!=undefined){PriNavImageContainer.find('.img-over-homepage').show();}else{PriNavImageContainer.find('.img-over').show();}}
function HidePriNavImageOver(PriNavImageContainer){if(TnT_CurrentLayout=="Homepage"&&PriNavImageContainer.find('.img-over-homepage').attr('src')!=undefined){PriNavImageContainer.find('.img-over-homepage').hide();}else{PriNavImageContainer.find('.img-over').hide();}}
function SetHeaderTextLinkColor(){var headerLink=$(".nav-wrapper .primary-nav .menu .drop-down ul li .item li").find('.primaryNavItemHeaderLink');var headerLinkColor;var headerLinkHoverColor;$("a.primaryNavItemHeaderLink, a.primaryNavItemSubHeaderLink").each(function(index){var objThis=$(this);if($(objThis).hasClass("primaryNavItemHeaderLink")){if($(objThis).attr('mouseoutcolor')!==undefined){headerLinkColor=$(this).attr('mouseoutcolor');}else{headerLinkColor=$(this).attr({'mouseoutcolor':$(objThis).css("color")});}}
if($(objThis).hasClass("primaryNavItemSubHeaderLink")){if($(objThis).attr('mouseoutcolor')!==undefined){headerLinkColor=$(this).attr('mouseoutcolor');}else{headerLinkColor=$(this).attr({'mouseoutcolor':$(objThis).css("color")});}}
$(objThis).css("cssText",";color:"+headerLinkColor+"!important");});$("a.primaryNavItemHeaderLink, a.primaryNavItemSubHeaderLink").hover(function(){if($(this).attr('mouseovercolor')!==undefined){headerLinkHoverColor=$(this).attr('mouseovercolor');}else{headerLinkHoverColor=$(this).attr({'mouseovercolor':$(this).css("color")});}
$(this).css("cssText",";color:"+headerLinkHoverColor+"!important");},function(){if($(this).attr('mouseoutcolor')!==undefined){headerLinkColor=$(this).attr('mouseoutcolor');}else{headerLinkColor=$(this).attr({'mouseoutcolor':$(this).css("color")});}
$(this).css("cssText",";color:"+headerLinkColor+"!important");});}
function RemoveTemporaryBackground(parentControl){var textLink=$(parentControl).find('.menu-textlink');if($(textLink).hasClass("menu-textlink")){if(textLink.attr('mouseoutbackground')!==undefined){textLink.css({'background-color':textLink.attr('mouseoutbackground')});}else{textLink.attr({'mouseoutbackground':$(".menu-textlink").css("background-color")});textLink.css({'background-color':textLink.attr('mouseoutbackground')});}}}
function RevertToImageLinks(){$("a.menu-textlink, a.menu-outlooktextlink").each(function(index){var objThis=$(this);var newlinkContent;if($(objThis).hasClass("menu-textlink")){newlinkContent=objThis.find('span').eq(1).html();objThis.removeClass('menu-textlink');}else{objThis.removeClass('menu-outlooktextlink');objThis.removeClass("outlook-pipeline");var spanCount=objThis.find('span').length;if(spanCount<=2){newlinkContent=objThis.find('span').eq(1).html();}else if(spanCount>=3){newlinkContent=objThis.find('span').eq(2).html();}}
objThis.empty();objThis.append(newlinkContent);objThis.removeClass('tk-imagefallback');});SelectOnLoadNavNode();}
function SetDropDownTimeOut(parentControl){__primaryNavTimer="";__primaryNavTimer=setTimeout(function(){CloseDropDownMenu(parentControl);},__timeConstant);$('.drop-down').mouseenter(function(){clearTimeout(__primaryNavTimer);}).mouseout(function(){clearTimeout(__primaryNavTimer);});clearTimeout(__timer);__timer=undefined;}
function OpenDropDownMenu(parentControl){if(parentControl!=undefined){if(__prevDropDownMenu!=undefined&&__tempPrimaryNavMenu!=null&&__tempPrimaryNavMenu!=parentControl){CloseDropDownMenu(__prevDropDownMenu);}
__tempPrimaryNavMenu=parentControl;var url=window.location.href.toString().toLowerCase();if(url.indexOf("/network/")<0){if(currentLayout=="Homepage"){if($(".LoginNavigationMenu").css('display')=='none'){$(".BtnToggleNavigation").css("background-position","0px -56px");}else{$(".BtnToggleNavigation").css("background-position","0px -84px");}
ChangeLoginColor();}else if(TnT_CurrentLayout=="CareersHomepage"){if($(".LoginNavigationMenu").css('display')=='none'){$(".BtnToggleNavigation").css("background-position","0px 0px");}else{$(".BtnToggleNavigation").css("background-position","0px -84px");}}}
if($(parentControl).find('ul li.column').length>0){$('.drop-down .sub-wrapper').attr('style','display:block!important;');}else{$('.drop-down .sub-wrapper').attr('style','display:none!important;');}
var textLink=$(parentControl).find('.menu-textlink');if($(textLink).hasClass("menu-textlink")){}else{$(parentControl).find('.img-out').hide();ShowPriNavImageOver($(parentControl));}
if(/msie|MSIE 6/.test(navigator.userAgent)){try{$("#sortSelect").css('visibility','hidden');}
catch(e){}}
if(!(($(parentControl).find('.drop-down .sub-wrapper .description').html()==""||$(parentControl).find('.drop-down .sub-wrapper .description').html()==null)&&($(parentControl).find('.drop-down .sub-wrapper ul li').length==0))){if($(parentControl).find('.drop-down').attr('visible').toLowerCase()=='true'){$(parentControl).find('.drop-down').show();}}
__hasOpenMenuDropdown=true;}
if(!(document.location.hostname.toLowerCase().indexOf("careers")||TnT_CurrentLayout=="Person"||TnT_CurrentLayout=="StandardNavigationPage"||TnT_CurrentLayout=="SiteSearch")){$(".banner").attr('style','z-index:1003');}
$(".PrivacyCookiePolicyHomepage").css('z-index','1004');}
function ChangeLoginColor(){$('.LoginNavigation .pipebar').css('border-left-color','#000');$('.divOrLiteral').css('color','black');$('.banner .user-status .UserControlLoginNote').css('color','#000');$('.page .user-status .LoginNavigation .LoginNote a, .divdelimiterLiteral').attr('style','color: #a13 !important;');}
function RevertLoginColor(){$('.LoginNavigation .pipebar').css('border-left-color','white');$('.divOrLiteral').css('color','white');$('.banner .user-status .UserControlLoginNote').css('color','#FFF');$('.page .user-status .LoginNavigation .LoginNote a, .divdelimiterLiteral').attr('style','color: #ade !important;');}
function CloseDropDownMenu(parentControl){var textLink;var url=window.location.href.toString().toLowerCase();if(url.indexOf("/network/")<0){if(TnT_CurrentLayout=="Homepage"||TnT_CurrentLayout=="CareersHomepage"){if($(".LoginNavigationMenu").css('display')=='none'){$(".BtnToggleNavigation").css("background-position","0px 0px");}else{$(".BtnToggleNavigation").css("background-position","0px -84px");}
RevertLoginColor();}}
if($(parentControl).hasClass("menu")){textLink=$(parentControl).find('.menu-textlink');}else{textLink=$(".primary-nav .menu").find('.menu-textlink');}
if($(textLink).hasClass("menu-textlink")){}else{HidePriNavImageOver($(".primary-nav .menu"));$(".primary-nav .menu").find('.img-out').show();}
$(".primary-nav .menu").find('.drop-down').hide();if(/msie|MSIE 6/.test(navigator.userAgent)){try{$("#sortSelect").css('visibility','visible');}
catch(e){}}
__timer=undefined;__hasOpenMenuDropdown=false;$(".banner").css('z-index','10');$(".PrivacyCookiePolicyHomepage").css('z-index','100');}
function SelectOnLoadNavNode(){if(!__hasOpenMenuDropdown){__selectedNavNodeOnload=$(".primary-nav a[currentNode='Yes']:last");if($(__selectedNavNodeOnload).hasClass("menu-textlink")){if(__selectedNavNodeOnload.attr('mouseoverbackground')!==undefined){__selectedNavNodeOnload.removeClass('menu-textlink-active');__selectedNavNodeOnload.css({'background-color':__selectedNavNodeOnload.attr('mouseoverbackground')});}else{__selectedNavNodeOnload.addClass('menu-textlink-active');__selectedNavNodeOnload.attr({'mouseoverbackground':$(".menu-textlink-active").css("background-color")});__selectedNavNodeOnload.css({'background-color':__selectedNavNodeOnload.attr('mouseoverbackground')});}}else{ShowPriNavImageOver(__selectedNavNodeOnLoad);__selectedNavNodeOnLoad.find('.img-out').hide();}}}
function DeselectOnLoadNavNode(){if($(__selectedNavNodeOnload).hasClass("menu-textlink")){__selectedNavNodeOnload.removeClass('menu-textlink-active');if(__selectedNavNodeOnload.attr('mouseoutbackground')!==undefined){__selectedNavNodeOnload.css({'background-color':__selectedNavNodeOnload.attr('mouseoutbackground')});}else{__selectedNavNodeOnload.attr({'mouseoutbackground':$(".menu-textlink").css("background-color")});__selectedNavNodeOnload.css({'background-color':__selectedNavNodeOnload.attr('mouseoutbackground')});}}else{HidePriNavImageOver(__selectedNavNodeOnLoad);__selectedNavNodeOnLoad.find('.img-out').show();}}
$(document).ready(function(){$("#PA_Click").click(function(event){ToggleLists(event);ReAlignFBLike();});$("#mvTab").click(function(event){TabClick("mv",event,false);ReAlignFBLike();});$("#msTab").click(function(event){TabClick("ms",event,false);ReAlignFBLike();});});function ReAlignFBLike(){var fb=$("#fbLike");var fbContainer=$("#fbLikeContainer");if(fb.length==1&&fbContainer.length==1){var fbLikePositionLeft=fbContainer.offset().left;var fbLikePositionTop=fbContainer.offset().top;if(/msie|MSIE 7/.test(navigator.userAgent)&&(typeof documentMode==="undefined")){fbLikePositionLeft=Math.round(fbContainer.offset().left/CommonGetIE7ZoomLevel());fbLikePositionTop=Math.round(fbContainer.offset().top/CommonGetIE7ZoomLevel());fb.css({"left":fbLikePositionLeft,"top":fbLikePositionTop});}
else{fb.css({"left":fbLikePositionLeft,"top":fbLikePositionTop});}}}
function CommonGetIE7ZoomLevel(){var zoomLevel=1;if(document.body.getBoundingClientRect){var rect=document.body.getBoundingClientRect();var physicalW=rect.right-rect.left;var logicalW=document.body.offsetWidth;zoomLevel=Math.round((physicalW/logicalW)*100)/100;}
return zoomLevel;}
var isClickedMV=false;var isClickedMS=false;function ToggleLists(event){try{var changeID=document.getElementById("PA_Click");if($(".pa-display-panel").is(":hidden")){SetPopularArticlesActiveTab(event);$(".display-pa").show();$(".pa-display-panel").show();changeID.className="pa-click-button";if((typeof TrackProductsImpression)=="function"){if(($('#mvTabBody div.pa-link').is(':visible')&&$('#msTabBody div.pa-link').is(':hidden'))||($('#mvTabBody div.pa-link').is(':visible')&&$('#msTabBody div.pa-link').is(':visible'))){$('#msTabBody div.pa-link').hide();$('#mvTabBody div.pa-link').show();$("#mvTab").addClass("activeTab");$("#mvTab a").addClass("active");$("#msTab").removeClass("activeTab");$("#msTab a").removeClass("active");window.HandleBodyClick(event);TrackProductsImpression(RetrieveProductsImpression($('div#mvTabBody').get()),true);isClickedMV=true;$('span[id*="lbl_mvTab"]').css('cursor','default');}else{$('#msTabBody div.pa-link').show();$('#mvTabBody div.pa-link').hide();$("#mvTab").removeClass("activeTab");$("#mvTab a").removeClass("active");$("#msTab").addClass("activeTab");$("#msTab a").addClass("active");window.HandleBodyClick(event);TrackProductsImpression(RetrieveProductsImpression($('div#msTabBody').get()),true);}}
var mvTabHeight=Math.round($('#mvTab a span').innerHeight());var msTabHeight=Math.round($('#msTab a span').innerHeight());var mvTabWidth=Math.round($('#mvTab').width());var msTabWidth=Math.round($('#msTab').width());if(mvTabHeight>msTabHeight){$('#mvTab').height(mvTabHeight);$('#msTab').height(mvTabHeight);}else{$('#mvTab').height(msTabHeight);$('#msTab').height(msTabHeight);}
$('#mvTab a span, #msTab a span').css('display','inline-block');if(/msie|MSIE 7/.test(navigator.userAgent)&&(typeof documentMode==="undefined")){$('#mvTab a span').width(mvTabWidth-10);$('#msTab a span').width(msTabWidth-10);}}else{$(".pa-display-panel").hide();$(".display-pa").hide();changeID.className="pa-click-expand";}}catch(e){}}
function TabClick(tabIdx,event,pageLoadFlag){if(pageLoadFlag==undefined){pageLoadFlag=false;}
try{$("#_currentTabIndex").val(tabIdx);var _token,_id;$.each(['mv','ms'],function(n,value){_token=value+"Tab";_id="#"+_token+"Body"
if(value!=tabIdx){if(!$(_id).is(":hidden")){$(_id).hide();$(_id+" .pa-link").hide();$("#"+_token).css("font-weight","normal");$("#"+_token).removeClass("activeTab");$("#"+_token+" a").removeClass("active");}}else{$(_id).show();$(_id+" .pa-link").show();$("#"+_token).css("font-weight","bold");$("#"+_token).addClass("activeTab");$("#"+_token+" a").addClass("active");if((typeof TrackProductsImpression)=="function"){if(value=='mv'){if(pageLoadFlag!=true&&!isClickedMV){window.HandleBodyClick(event);TrackProductsImpression(RetrieveProductsImpression($('div#mvTabBody').get()),true);isClickedMV=true;isClickedMS=false;$('span[id*="lbl_mvTab"]').css('cursor','default');$('span[id*="lbl_msTab"]').css('cursor','pointer');}}
else{if(pageLoadFlag!=true&&!isClickedMS){window.HandleBodyClick(event);TrackProductsImpression(RetrieveProductsImpression($('div#msTabBody').get()),true);isClickedMS=true;isClickedMV=false;$('span[id*="lbl_msTab"]').css('cursor','default');$('span[id*="lbl_mvTab"]').css('cursor','pointer');}}}}});}catch(e){}}
function SetPopularArticlesActiveTab(event){var _activeTab=$("#_currentTabIndex").val();var pageLoadFlag=true;if(!_activeTab){_activeTab="mv";}
TabClick(_activeTab,event,pageLoadFlag);}
$(document).ready(function(){RVA_Animation();});function RVA_Animation(){$("#RVA_Click").click(function(){if($(".display-rva").is(":hidden")){$('.display-rva').show();$('.recent-section .recentlink').css('display','block');var changeID;changeID=document.getElementById("RVA_Click");changeID.className="rva-click-expand";}else{$('.display-rva').hide();$('.recent-section .recentlink').css('display','none');$('.recent-section').removeAttr('style');var changeID;changeID=document.getElementById("RVA_Click");changeID.className="rva-click-button";}
ReAlignFBLike();});}
function AttachEventHandlersForRelatedTags(){$("a[name='modal']").hover(function(e){e.preventDefault();var maskHeight=$(document).height();var maskWidth=$(window).width();var id=$(this).attr("href");var leftpos=$(this).position().left;var documentMode=document.documentMode;var bottompos=$(this).position().top+$(this).height();if($.browser.safari)
$(id).css('top',bottompos);if(($.browser.version==7.0)||($.browser.version==6.0)){var anchorWidth=$(this).width();var anchorHeight=$(this).height();var marginLeft=anchorWidth;id=id.replace(window.location.href,"");}
CloseRTWindow();$(id).css({'left':leftpos});$(id).show();if($(id+" > .rtuc-details > #divViewThePageFor:first").html()!=""){if(($.browser.version==7.0)||($.browser.version==6.0))
$(id).css({'margin-top':"-57px"});else
$(id).css({'margin-top':"-72px"});}
if(($.browser.version==7.0)||($.browser.version==6.0)||(documentMode==9)){$(id).css({'width':"0"});var windowWidth;if(parseInt($(id+" > .rtuc-details > #divViewThePageFor:first").width())>parseInt($(id+" > .rtuc-details > #divSearchFor:first").width()))
windowWidth=CalculateTextWidth($(id+" > .rtuc-details > #divViewThePageFor:first"));else
windowWidth=CalculateTextWidth($(id+" > .rtuc-details > #divSearchFor:first"));$(id).css({'width':windowWidth});$(id).css({'margin-top':"-"+$(id).height()});}});$(document.body).click(function(){CloseRTWindow();});$('.rtuc-window').bind("mouseleave",function(){CloseRTWindow();});$("a[name='close']").click(function(e){e.preventDefault();CloseRTWindow();});$("#divViewThePageFor a[href='']").parent().html("");}
function CloseRTWindow(){$('.rtuc-window').hide();}
function CalculateTextWidth(el){var _width=0;var div=document.createElement('div');document.body.appendChild(div);$(div).css({position:'absolute',left:-1000,top:-1000,display:'none'});$(div).html($(el).text());var styles=['font-size','font-style','font-weight','font-family','line-height','text-transform','letter-spacing'];$(styles).each(function(){var s=this.toString();$(div).css({s:$(el).css(s)});});_width=$(div).outerWidth();$(div).remove();return _width;}
$(document).ready(function(){$('.now-hiring-title:empty').parent().parent().hide();$('.now-hiring-view:empty').parent().parent().hide();$('.now-hiring:hidden').parent().removeClass('box-in');$('.now-hiring:hidden').parent().html('');});$(document).ready(function(){var rvaheight=20;if(($.trim($('.subscriptions-link').text())=="")&&($.trim($('.recommended-jobs-link').text())=="")&&($.trim($('.interests-link').text())=="")){$('.cta-offerings-intro-text').hide();}
else{$('.cta-offerings-intro-text').filter(':empty').hide();}
if($('.rva-header-title').height()>rvaheight){$('.rva-header-title').addClass('rva-height');}
if($('.pa-header-title').height()>rvaheight){$('.pa-header-title').addClass('rva-height');}
$('.profile-cta-header, .profile-cta-text, .job-center-header, .job-center-intro, .job-center-link, .job-center-links, .newsletter-header, .newsletter-link, .interests-link, .recommended-jobs-link, .subcription-link, .cta-offerings-intro-text').each(function(){var value=$(this).text();if($(this).html()==null||$(this).html()=="&nbsp;"){$(this).hide();}
else{if($.trim($(this).text())==""){$(this).hide();}
else{$(this).filter(':empty').hide();}}});});function getByClass(matchClass,tag){var elems=document.getElementsByTagName(tag);var result;for(var i in elems){if((" "+elems[i].className+" ").indexOf(" "+matchClass+" ")>-1){result=elems[i];break;}}
return result;};function getCookie(key){var keyValue=document.cookie.match('(^|;) ?'+key+'=([^;]*)(;|$)');return keyValue?keyValue[2]:null;}
$(document).ready(function(){var cookieVal;var acnComCookieValues;var HasLoginID;var recognizedIntroText;var loginLink;var strLoginLink;var splittedLoginLink;var newURL;var newRecognizedIntroText;var myRegex='href\s*=\s*.*article-recommendations.aspx';cookieVal=getCookie("_ACCENTURE_COM_");HasLoginID=0;if((typeof(ZoneType)!='undefined')&&(cookieVal!=null)){acnComCookieValues=cookieVal.split('&');var authIntroText=getByClass('AuthenticatedIntroTextCss','div');var recoIntroText=getByClass('RecognizedIntroTextCss','div');if(authIntroText!=null&&recoIntroText!=null){for(ctr=0;ctr<acnComCookieValues.length;ctr++){var acnComCookieValue=acnComCookieValues[ctr].split('=');if(acnComCookieValue[0]=='LAST_LOGIN_ID'){HasLoginID=1;if(acnComCookieValue[1]!=""){if(ZoneType=='ADFS'){authIntroText.style.visibility="visible";authIntroText.style.display="block";recoIntroText.style.visibility="hidden";recoIntroText.style.display="none";}
else if(ZoneType=='Anon'){authIntroText.style.visibility="hidden";authIntroText.style.display="none";recoIntroText.style.visibility="visible";recoIntroText.style.display="block";recognizedIntroText=$('.RecognizedIntroTextCss').html();loginLink=recognizedIntroText.match(myRegex);strLoginLink=String(loginLink);splittedLoginLink=strLoginLink.split('"');if(splittedLoginLink[1]!=null||splittedLoginLink[1]!=undefined){if(splittedLoginLink[1].indexOf('article-recommendations.aspx')){newURL='href="https://'+String(document.domain)+splittedLoginLink[1]
newRecognizedIntroText=recognizedIntroText.replace(strLoginLink,newURL);$('.RecognizedIntroTextCss').html(newRecognizedIntroText);}}}
else if(ZoneType=='Edit'){authIntroText.style.visibility="visible";authIntroText.style.display="block";recoIntroText.style.visibility="visible";recoIntroText.style.display="block";}}
break;}}
if(HasLoginID==0){if(ZoneType=='Anon'){authIntroText.style.visibility="visible";authIntroText.style.display="block";recoIntroText.style.visibility="hidden";recoIntroText.style.display="none";}
if(ZoneType=='Edit'){authIntroText.style.visibility="visible";authIntroText.style.display="block";recoIntroText.style.visibility="visible";recoIntroText.style.display="block";}}}}});var obrDisplayCountryLanguageSelector=false;var isObrMouseOnHover=false;$('.obrCountry-language-selector .obrControl-selector .obrDrop-button').click(obrShowCountryLanguageSelector);$('.obrCountry-language-selector .obrControl-selector .obrIcon-flag').click(obrShowCountryLanguageSelector);$('.obrCountry-language-selector .obrControl-selector .obrDrop-button').mouseover(obrMouseHoverTrue);$('.obrCountry-language-selector .obrControl-selector .obrDrop-button').mouseout(obrMouseHoverFalse);$('.obrCountry-language-selector .obrControl-selector .obrIcon-flag').mouseover(obrMouseHoverTrue);$('.obrCountry-language-selector .obrControl-selector .obrIcon-flag').mouseout(obrMouseHoverFalse);$(".obrCountry-language-selector .obrDropdown-selector").mouseover(obrMouseHoverFalse);$(".obrCountry-language-selector .obrDropdown-selector").mouseout(obrMouseHoverFalse);function obrShowCountryLanguageSelector(){obrDisplayCountryLanguageSelector=true;isObrMouseOnHover=true;if($('.obrCountry-language-selector .obrDropdown-selector').is(":visible")){$('.obrCountry-language-selector .obrDropdown-selector').hide();}
else{$('.obrCountry-language-selector .obrDropdown-selector').show();}
if(/msie|MSIE 6/.test(navigator.userAgent)){$(document.frames.ddframe.document.body).css('border',"1px solid gray");}}
function obrMouseHoverTrue(){isObrMouseOnHover=true;}
function obrMouseHoverFalse(){isObrMouseOnHover=false;}
$(document).click(function(){if((obrDisplayCountryLanguageSelector==true)&&(isObrMouseOnHover==false)){$('.obrCountry-language-selector .obrDropdown-selector').hide();obrDisplayCountryLanguageSelector=false;}});$(document).ready(function(){if(/msie|MSIE 6/.test(navigator.userAgent)){$('.obrCountry-language-selector .obrDropdown-selector').css('padding',"0px");var countryLangSelector=$('.obrCountry-language-selector .obrDropdown-selector');var countryLangHeight=$('.obrCountry-language-selector .obrDropdown-selector').height();var countryLangWidth=$('.obrCountry-language-selector .obrDropdown-selector').width();for(c=0;c<countryLangSelector.length;c++){countryLangSelector[c].innerHTML=('<iframe id="ddframe" src="/_layouts/blank.htm" scrolling="no" frameborder="1"></iframe>'+countryLangSelector[c].innerHTML);var frameStyle=countryLangSelector[c].childNodes[0];countryLangHeight=countryLangHeight+10;countryLangWidth=countryLangWidth+1;frameStyle.style.height=countryLangHeight+"px";frameStyle.style.width=countryLangWidth+"px";}
$('.obrCountry-language-selector .obrDropdown-selector').css('height',countryLangHeight+"px");$('.obrCountry-language-selector .obrDropdown-selector').css('border',"none");$('.obrCountry-language-selector .obrDropdown-selector').css('margin-left',"-"+countryLangWidth+"px");$('.obrCountry-language-selector .obrDropdown-selector .obrCountryColumns').css('margin',"-"+countryLangHeight+"px 0px 0px 14px");}});$(function(){$(".viewSample").click(function(){var popupImg=new Image();popupImg.onload=function(){$("#divPopup").dialog({width:popupImg.width});$("#divPopup").dialog('open');$(".ui-dialog, .ui-dialog-title, #ui-dialog-title-divPopup, .ui-widget, .ui-widget-content, .ui-corner-all").css('width',$("#divPopup").width());}
popupImg.src=$("#divPopup img").attr('src');$(".ui-dialog, .ui-dialog-title").css('width',$("#divPopup").width());});if(/msie|MSIE 6/.test(navigator.userAgent)){$("#divPopup").prepend('<iframe id="iframe-popup" src="/_layouts/blank.htm" scrolling="no" frameborder="1"></iframe>');$("#divPopup img").css('cssText',';z-index:1;margin-top:-310px;');var iframe=$("#iframe-popup");iframe.css('width',$("#divPopup").width());if($("#iframe-popup").width()<301)
{iframe.css('width',$("#divPopup img").width());$("#divPopup img").css('cssText',';margin-top:-160px;');$("#iframe-popup").css('cssText',';margin-top:-22px;width:231px;height:200px;');}
iframe.css('height',$("#divPopup").height());$(".viewSample").hover(function(){$(".viewSample span").css('cssText',';color: #008899!important; text-decoration:underline;');},function(){$(".viewSample span").css('cssText',';color: #aa1134!important; text-decoration:none;');});}});function HpnCssOverrides(){if(clientBrowser.browser.ie==7){$('.inner-css-tab-pane .inner-css-tab-pane-content .linkContainer').attr('style','margin-left: 0;');}}
$(document).ready(function()
{if(document.location.href.toLowerCase().indexOf("/network/")>-1)
{HpnCssOverrides();if($('.save-wp-text').html()!=""&&$('.save-wp-text').html()!=null)
{$('.lit-save').removeClass("article-tools-save");$('.lit-save').addClass("article-tools-saved-icon-hpn");$('.lit-save').removeAttr('href');$('.lit-save').removeAttr('title');}}
else
{if($('.save-wp-text').html()!=""&&$('.save-wp-text').html()!=null)
{$('.lit-save').removeClass("article-tools-save");$('.lit-save').addClass("article-tools-saved-icon");$('.lit-save').removeAttr('href');$('.lit-save').removeAttr('title');}}
var MainContentsCurrentPosition="";$(".ShowCareersNewsletter").mouseenter(function(){if($(".main-contents")[0]){$('.profile-rollover').css("width",$('.profile-rollover-image').outerWidth()+"px");MainContentsCurrentPosition=$('.main-contents').css("position");$(".main-contents").css("position","static");}}).mouseleave(function(){if($(".main-contents")[0]){$(".main-contents").css("position",MainContentsCurrentPosition);}});});$(document).ready(function(){if($('.outlook-page').html()!=""&&$('.outlook-page').html()!=null){primaryOutlookNavMenuItems=$('div.linksHolder').find('.menu');primaryOutlookNavMenuItems.each(function(){var menuItemLink=$(this).find("a").first();var menuItemId=$(this).attr('id');menuItemLink.focus(function(){$(this).parent().find(".drop-down").show();$(".outlook.primary-nav .menu").find('.drop-down').css('margin-top','19px');primaryOutlookNavMenuItems.each(function(){if($(this).attr('id')!=menuItemId){$(this).find('.drop-down').hide();}});});});}else{primaryNavMenuItems=$('div.primary-nav').find('.menu');primaryNavMenuItems.each(function(){var menuItemLink=$(this).find("a").first();var menuItemId=$(this).attr('id');menuItemLink.focus(function(){$(this).parent().find(".drop-down").show();primaryNavMenuItems.each(function(){if($(this).attr('id')!=menuItemId){$(this).find('.drop-down').hide();}});});});$('div.primary-nav').find('.menu').last().find('a').last().focusout(function(){$('div.primary-nav').find('.menu').last().find('.drop-down').hide();});}});function CreateTabletScrollbar(containerToAddScrollBarTo,containerOfContentOuter,containerOfContentInner){var scrollHtml='<div class="scrollbar"><div class="track"><div class="thumb"><div class="end"></div></div></div></div>';if($(containerToAddScrollBarTo).length>0&&$(containerOfContentOuter).length>0&&$(containerOfContentInner).length>0){$(containerToAddScrollBarTo).append(scrollHtml);$(containerOfContentOuter).addClass('viewport');$(containerOfContentInner).addClass('overview');}}
function ActivateTabletScrollbar(containerContainingTinyScrollBar){if($(containerContainingTinyScrollBar).length>0){$(containerContainingTinyScrollBar).tinyscrollbar();}}
function CreateRefineSearchYourSelectionTabletScrollbars(){if(isTabletBrowser()){$('.filterItems .Category').find('.SubCategories').each(function(){if($(this).parents('.FilterCategoryTemplate').length<=0){var containerToAddScrollBarTo=$(this);var containerOfContentOuter=$(containerToAddScrollBarTo).find('.SubCategoryPanel');var containerOfContentInner=$(containerOfContentOuter).find('ul');CreateTabletScrollbar(containerToAddScrollBarTo,containerOfContentOuter,containerOfContentInner);}});}}
function ActivateRefineSearchYourSelectionTabletScrollbars(){if(isTabletBrowser()){$('.filterItems .Category').filter(':visible').find('.SubCategories').each(function(){if($(this).parents('.FilterCategoryTemplate').length<=0){var containerContainingTinyScrollBar=$(this);ActivateTabletScrollbar(containerContainingTinyScrollBar);}});}}
$(document).ready(function(){if(navigator.appVersion.indexOf("MSIE 10")!=-1||navigator.appVersion.indexOf("MSIE 9")!=-1)
{$('.stay-connected-title').css('width',parseInt($('.stay-connected-title').width()));$('.stay-connected ul li div.button a span strong').each(function(){$(this).css('width',parseInt($(this).width()));$(this).css('height',parseInt($(this).height()));});}
$(".stay-connected .parent .button a:has('.SC_podcasts_link')").css('padding','11px 17px 11px 18px');$(".stay-connected .parent .button a:has('.SC_newsletters_link')").css('padding','11px 16px 11px 17px');$(".stay-connected .parent .button a:has('.SC_blogs_link')").css('padding','11px 19px 11px 19px');$(".stay-connected .parent .button a:has('.SC_videos_link')").css('padding','11px 19px 11px 19px');$(".stay-connected .parent .button a:has('.SC_mobile_link')").css('padding','11px 22px 11px 22px');var banner=$(".bannersearch");if(banner!=null&&banner.length>0){var snav=$(".secondary-nav");var adjustWidth=$(".country-language-selector").outerWidth()+34+banner.outerWidth();$("#SecondaryNavLinks").css("max-width",(904-34-adjustWidth)+"px");snav.append(banner);$(".bannersearch").show();$(".country-language-selector").show();}
if($(".stay-connected").css('display')=="none"&&$(".footer").css('display')=="none"){$(".stay-connected-master").css('margin-bottom','10px');}
CheckCurrentPage();});function CheckCurrentPage(){$('#SecondaryNavLinks a, .footer-nav a , .button a').each(function(){var currAddress=window.location.pathname.toLowerCase();var linkContainer=$(this);var parentContainer=$(this).parent();var currentLink=linkContainer.attr('href').toLowerCase();if(currAddress==currentLink){DisableLink(parentContainer,linkContainer);}});}
function DisableLink(parentContainer,obj){var classSelector=parentContainer[0].className;if(classSelector==""){classSelector=parentContainer[0].id;}
switch(classSelector){case"footer-nav fsize-c":obj.replaceWith('<span class="CurrentFooter">'+obj.html()+'</span>');break;case"SecondaryNavLinks":var link=document.getElementById(obj[0].id);var label=document.createElement('span');label.className="CurrentSecondaryNav";label.innerHTML=link.innerHTML;link.parentNode.replaceChild(label,link);break;case"button":obj.replaceWith('<div class="CurrentStayConn">'+obj.html()+'</div>');break;default:break;}}
function GetRecentViewedJobs(contextId){var WebUrlJson=""
if(typeof(recentlyViewedWebService)!='undefined'&&recentlyViewedWebService.length>0){WebUrlJson=recentlyViewedWebService.replace(/ /g,'');WebUrlJson=WebUrlJson.replace("<CONTEXTID>",contextId);WebUrlJson=WebUrlJson.replace("<COUNTRY>",typeof(recentlyViewedCountry)!='undefined'?recentlyViewedCountry:'');WebUrlJson=UpdatePortNumber(WebUrlJson);}else{HideRVAjobsSection();DisplayHideRecentlySectionOnLoad();return false;}
$.ajax({url:WebUrlJson,contentType:"application/json; charset=utf-8",dataType:"jsonp",jsonpCallback:'DisplayRecentlyViewedJobs',jsonp:'callback',timeout:300000,error:function(jqXHR,textStatus,errorThrown){HideRVAjobsSection();DisplayHideRecentlySectionOnLoad();}});}
function GetRecommendedJobs(contextId){var WebUrlJson=""
if(typeof(recommendedWebService)!='undefined'&&recommendedWebService.length>0){WebUrlJson=recommendedWebService.replace(/ /g,'');WebUrlJson=WebUrlJson.replace("<CONTEXTID>",contextId);WebUrlJson=WebUrlJson.replace("<COUNTRY>",typeof(recommendedCountry)!='undefined'?recommendedCountry:'');WebUrlJson=UpdatePortNumber(WebUrlJson);}else{HideRecommendedSection();DisplayHideRecommendedSectionOnLoad();return false;}
$.ajax({url:WebUrlJson,contentType:"application/json; charset=utf-8",dataType:"jsonp",jsonpCallback:'DisplayRecommendedJobs',jsonp:'callback',timeout:300000,error:function(jqXHR,textStatus,errorThrown){HideRecommendedSection();DisplayHideRecommendedSectionOnLoad();}});}
function getContextId(){var contextId='';var cookieOmnitureVisitor='';if(typeof s!='undefined'){cookieOmnitureVisitor=s.c_r('s_vi');}else{$.cookie('s_vi');}
if(cookieOmnitureVisitor!=null&&cookieOmnitureVisitor.length>0){var temp=cookieOmnitureVisitor.substring(cookieOmnitureVisitor.indexOf('|')+1,cookieOmnitureVisitor.lastIndexOf('['));temp=temp.toLowerCase();contextId=temp;}else{contextId="null";}
return contextId;}
function UpdatePortNumber(WebUrlJson){var HTTP_DataPullPortNumber="8082";var HTTPS_DataPullPortNumber="8443";if(window.location.protocol.toLowerCase()=="http:"){WebUrlJson=WebUrlJson.replace("<PORTNUMBER>",HTTP_DataPullPortNumber);}else{WebUrlJson=WebUrlJson.replace("<PORTNUMBER>",HTTPS_DataPullPortNumber);}
return WebUrlJson;}
$(document).ready(function(){var contextId=getContextId();SetDefaultView();if(typeof(isSuggestedVisible)!='undefined'){if(isSuggestedVisible=="True"&&contextId!='null'){GetRecommendedJobs(contextId);}else{DisplayHideRecommendedSectionOnLoad();}}else{DisplayHideRecommendedSectionOnLoad();}
if(typeof(isRecentlyViewedJobsVisible)!='undefined'){if(isRecentlyViewedJobsVisible=="True"&&contextId!='null'){GetRecentViewedJobs(contextId);}else{DisplayHideRecentlySectionOnLoad();}}else{DisplayHideRecentlySectionOnLoad();}});function SetDefaultView(){$('.jobsOpening-white-arrow').css('background-position','0 0');$('.latestJobsArrow').css('background-position','0 0');$('.recommendedJobsArrow').css('background-position','0 -10px');if(TnT_CurrentLayout=="CareersJobSearch"||TnT_CurrentLayout=="CareersJobPostingLayout"){if(TnT_CurrentLayout=="CareersJobSearch"){$('.latestJobsSectionContainer').remove();}else{$('.latestJobsSectionClass').hide();}
$('.recommendedJobsClass').show();$('.latestJobsArrow').css('background-position','0 -10px');$('.recommendedJobsArrow').css('background-position','0 0');}}
function HideRecommendedSection(){$('.recommendedSectionContainer').remove();}
function HideRVAjobsSection(){$('.RVJobsContainer').remove();}
function DisplayHideRecommendedSectionOnLoad(){if($('.latest-jobs > li').length==0){$('.latestJobsSectionContainer').remove();}
if($('.recommended-jobs > li').length==0||isSuggestedVisible=="False"){HideRecommendedSection()}
if($('.latest-jobs > li').length==0&&$('.recommended-jobs > li').length==0){$('.jobOpenings').remove();}else{$('.jobOpenings').show();}}
function DisplayHideRecentlySectionOnLoad(){if($('.careers-rv-jobs .RV-Job-Item').html()==null||isRecentlyViewedJobsVisible=="False"){HideRVAjobsSection();}
if($('.RVJobsContainer').html()==null&&$('.RVPagesContainer').html()==null){$('.RV-careers').remove();}else{$('.RV-careers').show();}}
function DisplayOrHideSection(sectionID,arrowImageClass){var childContainer='.'+sectionID+'Class';if($(childContainer).is(":hidden")){$(childContainer).show();$('.'+arrowImageClass).css('background-position','0 0');}else{$(childContainer).hide();$('.'+arrowImageClass).css('background-position','0 -10px');}}
function showMoreSuggested(){$('#recommended-jobs-min').hide();$('.moreSuggestedText').hide();$('#recommended-jobs-max').show();}
function DisplayRecommendedJobs(jsonObj){var listRecommended=[];var recommendedItemsMin=[];var recommendedItemsMax=[];var template="#recommendedJobsPartialTemplate";var placeholderMin="#recommended-jobs-min";var placeholderMax="#recommended-jobs-max";if(typeof(maxRecommendedJobs)!='undefined'&&typeof(minRecommendedJobs)!='undefined'){if(maxRecommendedJobs>0&&jsonObj._entries.length>0){if(minRecommendedJobs>maxRecommendedJobs){minRecommendedJobs=maxRecommendedJobs;}
if(jsonObj._entries.length<maxRecommendedJobs){maxRecommendedJobs=jsonObj._entries.length;}
listRecommended=typeof(jsonObj)!='undefined'?jsonObj._entries:[];for(var i=0;i<minRecommendedJobs;i++){recommendedItemsMin[recommendedItemsMin.length]=listRecommended[i];}
for(var i=0;i<maxRecommendedJobs;i++){recommendedItemsMax[recommendedItemsMax.length]=listRecommended[i];}
var template=$(template);var nodeMin=$(template).bindTo(recommendedItemsMin);$(nodeMin).appendTo(placeholderMin);var nodeMax=$(template).bindTo(recommendedItemsMax);$(nodeMax).appendTo(placeholderMax);$('#recommended-jobs-min li, #recommended-jobs-max li').each(function(){var linkText=$(this).find('a').eq(0);$(linkText).attr('title',linkText.text().toString());});if(jsonObj._entries.length>minRecommendedJobs&&maxRecommendedJobs>minRecommendedJobs){$('.moreSuggestedText').show();}}}
DisplayHideRecommendedSectionOnLoad();}
function DisplayRecentlyViewedJobs(jsonObj){var listRecentlyViewed=[];var RecentlyViewedItems=[];var template="#RecentlyViewedJobsTemplate";var placeholder=".careers-rv-jobs";if(typeof(maxRecentlyViewedJobs)!='undefined'){if(maxRecentlyViewedJobs>0&&jsonObj._entries.length>0){if(jsonObj._entries.length<maxRecentlyViewedJobs){maxRecentlyViewedJobs=jsonObj._entries.length;}
listRecentlyViewed=typeof(jsonObj)!='undefined'?jsonObj._entries:[];for(var i=0;i<maxRecentlyViewedJobs;i++){RecentlyViewedItems[RecentlyViewedItems.length]=listRecentlyViewed[i];}
var template=$(template);var node=$(template).bindTo(RecentlyViewedItems);$(node).appendTo(placeholder);$('.careers-rv-jobs .RV-Job-Item').each(function(){var linkText=$(this).find('a').eq(0);$(linkText).attr('title',linkText.text().toString());});}}
DisplayHideRecentlySectionOnLoad();}